from qfmt import C

# Hard ladder rungs. Answer lists: index 0 is always correct.

L11 = [
    C("In which year was the Peace of Westphalia signed?",
      ["1648", "1618", "1701", "1555"],
      "W którym roku zawarto pokój westfalski?",
      ["1648", "1618", "1701", "1555"],
      "In welchem Jahr wurde der Westfälische Frieden geschlossen?",
      ["1648", "1618", "1701", "1555"]),
    C("Who wrote the novel The Magic Mountain?",
      ["Thomas Mann", "Hermann Hesse", "Franz Kafka", "Robert Musil"],
      "Kto napisał powieść Czarodziejska góra?",
      ["Thomas Mann", "Hermann Hesse", "Franz Kafka", "Robert Musil"],
      "Wer schrieb den Roman Der Zauberberg?",
      ["Thomas Mann", "Hermann Hesse", "Franz Kafka", "Robert Musil"]),
    C("What is the atomic number of gold?",
      ["79", "47", "82", "29"],
      "Jaka jest liczba atomowa złota?",
      ["79", "47", "82", "29"],
      "Welche Ordnungszahl hat Gold?",
      ["79", "47", "82", "29"]),
    C("Who composed the opera The Bartered Bride?",
      ["Bedřich Smetana", "Antonín Dvořák", "Leoš Janáček", "Franz Liszt"],
      "Kto skomponował operę Sprzedana narzeczona?",
      ["Bedřich Smetana", "Antonín Dvořák", "Leoš Janáček", "Franz Liszt"],
      "Wer komponierte die Oper Die verkaufte Braut?",
      ["Bedřich Smetana", "Antonín Dvořák", "Leoš Janáček", "Franz Liszt"]),
    C("In which year did the Battle of Grunwald take place?",
      ["1410", "1386", "1453", "1525"],
      "W którym roku stoczono bitwę pod Grunwaldem?",
      ["1410", "1386", "1453", "1525"],
      "In welchem Jahr fand die Schlacht bei Grunwald statt?",
      ["1410", "1386", "1453", "1525"]),
    C("Werner Heisenberg is best known for formulating which principle?",
      ["Uncertainty principle", "Exclusion principle", "Equivalence principle", "Correspondence principle"],
      "Werner Heisenberg jest znany przede wszystkim ze sformułowania której zasady?",
      ["zasada nieoznaczoności", "zakaz Pauliego", "zasada równoważności", "zasada odpowiedniości"],
      "Wofür ist Werner Heisenberg vor allem bekannt?",
      ["Unschärferelation", "Ausschlussprinzip", "Äquivalenzprinzip", "Korrespondenzprinzip"]),
    C("Who painted The Night Watch?",
      ["Rembrandt", "Johannes Vermeer", "Peter Paul Rubens", "Frans Hals"],
      "Kto namalował Straż nocną?",
      ["Rembrandt", "Johannes Vermeer", "Peter Paul Rubens", "Frans Hals"],
      "Wer malte Die Nachtwache?",
      ["Rembrandt", "Johannes Vermeer", "Peter Paul Rubens", "Frans Hals"]),
    C("Who received the first Nobel Prize in Physics, in 1901?",
      ["Wilhelm Röntgen", "Marie Curie", "Hendrik Lorentz", "Max Planck"],
      "Kto otrzymał pierwszą Nagrodę Nobla w dziedzinie fizyki, w 1901 roku?",
      ["Wilhelm Röntgen", "Maria Skłodowska-Curie", "Hendrik Lorentz", "Max Planck"],
      "Wer erhielt 1901 den ersten Nobelpreis für Physik?",
      ["Wilhelm Röntgen", "Marie Curie", "Hendrik Lorentz", "Max Planck"]),
    C("Who wrote the novel The Trial?",
      ["Franz Kafka", "Thomas Mann", "Stefan Zweig", "Joseph Roth"],
      "Kto napisał powieść Proces?",
      ["Franz Kafka", "Thomas Mann", "Stefan Zweig", "Joseph Roth"],
      "Wer schrieb den Roman Der Prozess?",
      ["Franz Kafka", "Thomas Mann", "Stefan Zweig", "Joseph Roth"]),
    C("What is the chemical symbol for tungsten?",
      ["W", "Tu", "Tg", "Tn"],
      "Jaki jest symbol chemiczny wolframu?",
      ["W", "Tu", "Tg", "Tn"],
      "Was ist das chemische Symbol für Wolfram?",
      ["W", "Tu", "Tg", "Tn"]),
    C("Which river is the longest in Europe?",
      ["Volga", "Danube", "Dnieper", "Rhine"],
      "Która rzeka jest najdłuższa w Europie?",
      ["Wołga", "Dunaj", "Dniepr", "Ren"],
      "Welcher Fluss ist der längste Europas?",
      ["Wolga", "Donau", "Dnepr", "Rhein"]),
    C("Who wrote Thus Spoke Zarathustra?",
      ["Friedrich Nietzsche", "Arthur Schopenhauer", "Søren Kierkegaard", "Georg Wilhelm Friedrich Hegel"],
      "Kto napisał Tako rzecze Zaratustra?",
      ["Friedrich Nietzsche", "Arthur Schopenhauer", "Søren Kierkegaard", "Georg Wilhelm Friedrich Hegel"],
      "Wer schrieb Also sprach Zarathustra?",
      ["Friedrich Nietzsche", "Arthur Schopenhauer", "Søren Kierkegaard", "Georg Wilhelm Friedrich Hegel"]),
    C("In which year was the Great Fire of London?",
      ["1666", "1642", "1688", "1605"],
      "W którym roku wybuchł Wielki Pożar Londynu?",
      ["1666", "1642", "1688", "1605"],
      "In welchem Jahr wütete der Große Brand von London?",
      ["1666", "1642", "1688", "1605"]),
    C("Who composed Carmina Burana?",
      ["Carl Orff", "Richard Strauss", "Gustav Holst", "Igor Stravinsky"],
      "Kto skomponował Carmina Burana?",
      ["Carl Orff", "Richard Strauss", "Gustav Holst", "Igor Strawinski"],
      "Wer komponierte Carmina Burana?",
      ["Carl Orff", "Richard Strauss", "Gustav Holst", "Igor Strawinsky"]),
    C("What is the capital of Bhutan?",
      ["Thimphu", "Kathmandu", "Dhaka", "Colombo"],
      "Jaka jest stolica Bhutanu?",
      ["Thimphu", "Katmandu", "Dhaka", "Kolombo"],
      "Was ist die Hauptstadt Bhutans?",
      ["Thimphu", "Kathmandu", "Dhaka", "Colombo"]),
    C("Who was the last tsar of Russia?",
      ["Nicholas II", "Alexander III", "Peter III", "Ivan IV"],
      "Kto był ostatnim carem Rosji?",
      ["Mikołaj II", "Aleksander III", "Piotr III", "Iwan IV"],
      "Wer war der letzte Zar Russlands?",
      ["Nikolaus II.", "Alexander III.", "Peter III.", "Iwan IV."]),
    C("In which year was the Battle of Lepanto fought?",
      ["1571", "1492", "1588", "1526"],
      "W którym roku stoczono bitwę pod Lepanto?",
      ["1571", "1492", "1588", "1526"],
      "In welchem Jahr fand die Seeschlacht von Lepanto statt?",
      ["1571", "1492", "1588", "1526"]),
    C("Which element has the atomic number 26?",
      ["Iron", "Copper", "Zinc", "Nickel"],
      "Który pierwiastek ma liczbę atomową 26?",
      ["żelazo", "miedź", "cynk", "nikiel"],
      "Welches Element hat die Ordnungszahl 26?",
      ["Eisen", "Kupfer", "Zink", "Nickel"]),
    C("Who wrote The Name of the Rose?",
      ["Umberto Eco", "Italo Calvino", "Alberto Moravia", "Primo Levi"],
      "Kto napisał Imię róży?",
      ["Umberto Eco", "Italo Calvino", "Alberto Moravia", "Primo Levi"],
      "Wer schrieb Der Name der Rose?",
      ["Umberto Eco", "Italo Calvino", "Alberto Moravia", "Primo Levi"]),
    C("What is the approximate value of Avogadro's number?",
      ["6.022 x 10^23", "3.00 x 10^8", "1.60 x 10^-19", "6.626 x 10^-34"],
      "Ile wynosi w przybliżeniu liczba Avogadra?",
      ["6.022 x 10^23", "3.00 x 10^8", "1.60 x 10^-19", "6.626 x 10^-34"],
      "Wie groß ist ungefähr die Avogadro-Konstante?",
      ["6.022 x 10^23", "3.00 x 10^8", "1.60 x 10^-19", "6.626 x 10^-34"]),
    C("In which city did the 1814-1815 congress that redrew Europe after Napoleon meet?",
      ["Vienna", "Paris", "Berlin", "London"],
      "W którym mieście obradował kongres z lat 1814-1815, który na nowo wytyczył mapę Europy po Napoleonie?",
      ["Wiedeń", "Paryż", "Berlin", "Londyn"],
      "In welcher Stadt tagte 1814/15 der Kongress, der Europa nach Napoleon neu ordnete?",
      ["Wien", "Paris", "Berlin", "London"]),
    C("In Greek mythology, who ferries the dead across the Styx?",
      ["Charon", "Hades", "Cerberus", "Thanatos"],
      "Kto w mitologii greckiej przewozi zmarłych przez Styks?",
      ["Charon", "Hades", "Cerber", "Tanatos"],
      "Wer setzt in der griechischen Mythologie die Toten über den Styx?",
      ["Charon", "Hades", "Kerberos", "Thanatos"]),
    C("Which philosopher wrote Critique of Pure Reason?",
      ["Immanuel Kant", "Georg Wilhelm Friedrich Hegel", "David Hume", "John Locke"],
      "Który filozof napisał Krytykę czystego rozumu?",
      ["Immanuel Kant", "Georg Wilhelm Friedrich Hegel", "David Hume", "John Locke"],
      "Welcher Philosoph schrieb die Kritik der reinen Vernunft?",
      ["Immanuel Kant", "Georg Wilhelm Friedrich Hegel", "David Hume", "John Locke"]),
    C("The Masurian Lake District lies mainly in which country?",
      ["Poland", "Finland", "Sweden", "Lithuania"],
      "Na terenie którego kraju leży głównie Kraina Wielkich Jezior Mazurskich?",
      ["Polska", "Finlandia", "Szwecja", "Litwa"],
      "In welchem Land liegt vor allem die masurische Seenplatte?",
      ["Polen", "Finnland", "Schweden", "Litauen"]),
    C("Who composed the New World Symphony?",
      ["Antonín Dvořák", "Bedřich Smetana", "Johannes Brahms", "Gustav Mahler"],
      "Kto skomponował Symfonię z Nowego Świata?",
      ["Antonín Dvořák", "Bedřich Smetana", "Johannes Brahms", "Gustav Mahler"],
      "Wer komponierte die Sinfonie aus der Neuen Welt?",
      ["Antonín Dvořák", "Bedřich Smetana", "Johannes Brahms", "Gustav Mahler"]),
    C("In which year was the Battle of Trafalgar fought?",
      ["1805", "1800", "1812", "1798"],
      "W którym roku stoczono bitwę pod Trafalgarem?",
      ["1805", "1800", "1812", "1798"],
      "In welchem Jahr fand die Schlacht von Trafalgar statt?",
      ["1805", "1800", "1812", "1798"]),
]

L12 = [
    C("In which year did the Battle of White Mountain take place?",
      ["1620", "1618", "1648", "1683"],
      "W którym roku stoczono bitwę pod Białą Górą?",
      ["1620", "1618", "1648", "1683"],
      "In welchem Jahr fand die Schlacht am Weißen Berg statt?",
      ["1620", "1618", "1648", "1683"]),
    C("Who wrote The World as Will and Representation?",
      ["Arthur Schopenhauer", "Friedrich Nietzsche", "Georg Wilhelm Friedrich Hegel", "Johann Gottlieb Fichte"],
      "Kto napisał Świat jako wola i przedstawienie?",
      ["Arthur Schopenhauer", "Friedrich Nietzsche", "Georg Wilhelm Friedrich Hegel", "Johann Gottlieb Fichte"],
      "Wer schrieb Die Welt als Wille und Vorstellung?",
      ["Arthur Schopenhauer", "Friedrich Nietzsche", "Georg Wilhelm Friedrich Hegel", "Johann Gottlieb Fichte"]),
    C("Which isotope of uranium is the principal fissile isotope in most nuclear reactors?",
      ["U-235", "U-238", "U-234", "U-233"],
      "Który izotop uranu jest głównym izotopem rozszczepialnym w większości reaktorów jądrowych?",
      ["U-235", "U-238", "U-234", "U-233"],
      "Welches Uranisotop ist das wichtigste spaltbare Isotop in den meisten Kernreaktoren?",
      ["U-235", "U-238", "U-234", "U-233"]),
    C("Who painted The Ambassadors, the double portrait with an anamorphic skull?",
      ["Hans Holbein the Younger", "Albrecht Dürer", "Jan van Eyck", "Lucas Cranach the Elder"],
      "Kto namalował Ambasadorów, podwójny portret z anamorficzną czaszką?",
      ["Hans Holbein młodszy", "Albrecht Dürer", "Jan van Eyck", "Lucas Cranach starszy"],
      "Wer malte Die Gesandten, das Doppelporträt mit dem anamorphen Schädel?",
      ["Hans Holbein der Jüngere", "Albrecht Dürer", "Jan van Eyck", "Lucas Cranach der Ältere"]),
    C("In which year was the Austro-Hungarian Compromise, the Ausgleich, signed?",
      ["1867", "1848", "1871", "1918"],
      "W którym roku zawarto ugodę austro-węgierską, zwaną Ausgleich?",
      ["1867", "1848", "1871", "1918"],
      "In welchem Jahr wurde der österreichisch-ungarische Ausgleich geschlossen?",
      ["1867", "1848", "1871", "1918"]),
    C("Who composed the opera Rusalka?",
      ["Antonín Dvořák", "Bedřich Smetana", "Leoš Janáček", "Pyotr Tchaikovsky"],
      "Kto skomponował operę Rusalka?",
      ["Antonín Dvořák", "Bedřich Smetana", "Leoš Janáček", "Piotr Czajkowski"],
      "Wer komponierte die Oper Rusalka?",
      ["Antonín Dvořák", "Bedřich Smetana", "Leoš Janáček", "Pjotr Tschaikowski"]),
    C("Which mathematician proved that there is no general algebraic solution to quintic equations?",
      ["Niels Henrik Abel", "Évariste Galois", "Carl Friedrich Gauss", "Leonhard Euler"],
      "Który matematyk wykazał, że nie istnieje ogólne rozwiązanie algebraiczne równań piątego stopnia?",
      ["Niels Henrik Abel", "Évariste Galois", "Carl Friedrich Gauss", "Leonhard Euler"],
      "Welcher Mathematiker bewies, dass es keine allgemeine algebraische Lösung für Gleichungen fünften Grades gibt?",
      ["Niels Henrik Abel", "Évariste Galois", "Carl Friedrich Gauss", "Leonhard Euler"]),
    C("The Peace of Augsburg of 1555 established which principle?",
      ["Cuius regio, eius religio", "Extra ecclesiam nulla salus", "Sola scriptura", "Deus vult"],
      "Pokój augsburski z 1555 roku ustanowił którą zasadę?",
      ["Cuius regio, eius religio", "Extra ecclesiam nulla salus", "Sola scriptura", "Deus vult"],
      "Der Augsburger Religionsfrieden von 1555 etablierte welchen Grundsatz?",
      ["Cuius regio, eius religio", "Extra ecclesiam nulla salus", "Sola scriptura", "Deus vult"]),
    C("Who wrote the epic Pan Tadeusz?",
      ["Adam Mickiewicz", "Juliusz Słowacki", "Zygmunt Krasiński", "Cyprian Norwid"],
      "Kto napisał epopeję Pan Tadeusz?",
      ["Adam Mickiewicz", "Juliusz Słowacki", "Zygmunt Krasiński", "Cyprian Norwid"],
      "Wer schrieb das Epos Herr Thaddäus?",
      ["Adam Mickiewicz", "Juliusz Słowacki", "Zygmunt Krasiński", "Cyprian Norwid"]),
    C("What is the capital of Moldova?",
      ["Chișinău", "Tbilisi", "Yerevan", "Baku"],
      "Jaka jest stolica Mołdawii?",
      ["Kiszyniów", "Tbilisi", "Erywań", "Baku"],
      "Was ist die Hauptstadt der Republik Moldau?",
      ["Kischinau", "Tiflis", "Jerewan", "Baku"]),
    C("Who discovered the electron?",
      ["J. J. Thomson", "Ernest Rutherford", "Niels Bohr", "James Chadwick"],
      "Kto odkrył elektron?",
      ["J. J. Thomson", "Ernest Rutherford", "Niels Bohr", "James Chadwick"],
      "Wer entdeckte das Elektron?",
      ["J. J. Thomson", "Ernest Rutherford", "Niels Bohr", "James Chadwick"]),
    C("In which year did John III Sobieski relieve the siege of Vienna?",
      ["1683", "1648", "1701", "1620"],
      "W którym roku Jan III Sobieski odsieczą wiedeńską przerwał oblężenie Wiednia?",
      ["1683", "1648", "1701", "1620"],
      "In welchem Jahr entsetzte Johann III. Sobieski Wien?",
      ["1683", "1648", "1701", "1620"]),
    C("Who painted The Garden of Earthly Delights?",
      ["Hieronymus Bosch", "Pieter Bruegel the Elder", "Albrecht Dürer", "Matthias Grünewald"],
      "Kto namalował Ogród rozkoszy ziemskich?",
      ["Hieronim Bosch", "Pieter Bruegel starszy", "Albrecht Dürer", "Matthias Grünewald"],
      "Wer malte den Garten der Lüste?",
      ["Hieronymus Bosch", "Pieter Bruegel der Ältere", "Albrecht Dürer", "Matthias Grünewald"]),
    C("About how long is the half-life of carbon-14?",
      ["5730 years", "12 years", "4.5 billion years", "1600 years"],
      "Ile wynosi w przybliżeniu okres połowicznego rozpadu węgla-14?",
      ["5730 lat", "12 lat", "4,5 miliarda lat", "1600 lat"],
      "Wie lang ist ungefähr die Halbwertszeit von Kohlenstoff-14?",
      ["5730 Jahre", "12 Jahre", "4,5 Milliarden Jahre", "1600 Jahre"]),
    C("Who wrote The Structure of Scientific Revolutions and popularized the term paradigm shift?",
      ["Thomas Kuhn", "Karl Popper", "Imre Lakatos", "Paul Feyerabend"],
      "Kto napisał Strukturę rewolucji naukowych i spopularyzował pojęcie zmiany paradygmatu?",
      ["Thomas Kuhn", "Karl Popper", "Imre Lakatos", "Paul Feyerabend"],
      "Wer schrieb Die Struktur wissenschaftlicher Revolutionen und popularisierte den Begriff des Paradigmenwechsels?",
      ["Thomas Kuhn", "Karl Popper", "Imre Lakatos", "Paul Feyerabend"]),
    C("The Strait of Hormuz connects the Persian Gulf with which body of water?",
      ["Gulf of Oman", "Red Sea", "Arabian Sea", "Mediterranean Sea"],
      "Cieśnina Ormuz łączy Zatokę Perską z którym akwenem?",
      ["Zatoka Omańska", "Morze Czerwone", "Morze Arabskie", "Morze Śródziemne"],
      "Die Straße von Hormus verbindet den Persischen Golf mit welchem Gewässer?",
      ["Golf von Oman", "Rotes Meer", "Arabisches Meer", "Mittelmeer"]),
    C("Which chemist published the periodic table in 1869?",
      ["Dmitri Mendeleev", "Julius Lothar Meyer", "John Newlands", "Antoine Lavoisier"],
      "Który chemik opublikował układ okresowy w 1869 roku?",
      ["Dmitrij Mendelejew", "Julius Lothar Meyer", "John Newlands", "Antoine Lavoisier"],
      "Welcher Chemiker veröffentlichte 1869 das Periodensystem?",
      ["Dmitri Mendelejew", "Julius Lothar Meyer", "John Newlands", "Antoine Lavoisier"]),
    C("In which modern country are the ruins of ancient Carthage?",
      ["Tunisia", "Libya", "Algeria", "Morocco"],
      "W którym współczesnym państwie leżą ruiny starożytnej Kartaginy?",
      ["Tunezja", "Libia", "Algieria", "Maroko"],
      "In welchem heutigen Staat liegen die Ruinen des antiken Karthago?",
      ["Tunesien", "Libyen", "Algerien", "Marokko"]),
    C("Who wrote Being and Time?",
      ["Martin Heidegger", "Jean-Paul Sartre", "Edmund Husserl", "Karl Jaspers"],
      "Kto napisał Bycie i czas?",
      ["Martin Heidegger", "Jean-Paul Sartre", "Edmund Husserl", "Karl Jaspers"],
      "Wer schrieb Sein und Zeit?",
      ["Martin Heidegger", "Jean-Paul Sartre", "Edmund Husserl", "Karl Jaspers"]),
    C("The Battle of Mohacs in 1526 was a decisive Ottoman victory over which kingdom?",
      ["Hungary", "Poland", "Austria", "Serbia"],
      "Bitwa pod Mohaczem w 1526 roku była decydującym zwycięstwem Osmanów nad którym królestwem?",
      ["Węgry", "Polska", "Austria", "Serbia"],
      "Die Schlacht bei Mohács 1526 war ein entscheidender osmanischer Sieg über welches Königreich?",
      ["Ungarn", "Polen", "Österreich", "Serbien"]),
    C("Which particle did James Chadwick discover in 1932?",
      ["Neutron", "Proton", "Positron", "Neutrino"],
      "Jaką cząstkę odkrył James Chadwick w 1932 roku?",
      ["neutron", "proton", "pozyton", "neutrino"],
      "Welches Teilchen entdeckte James Chadwick 1932?",
      ["Neutron", "Proton", "Positron", "Neutrino"]),
    C("Who wrote The Unbearable Lightness of Being?",
      ["Milan Kundera", "Václav Havel", "Bohumil Hrabal", "Jaroslav Hašek"],
      "Kto jest autorem Nieznośnej lekkości bytu?",
      ["Milan Kundera", "Václav Havel", "Bohumil Hrabal", "Jaroslav Hašek"],
      "Wer ist der Autor von Die unerträgliche Leichtigkeit des Seins?",
      ["Milan Kundera", "Václav Havel", "Bohumil Hrabal", "Jaroslav Hašek"]),
    C("Which river flows through Prague?",
      ["Vltava", "Elbe", "Morava", "Danube"],
      "Która rzeka przepływa przez Pragę?",
      ["Wełtawa", "Łaba", "Morawa", "Dunaj"],
      "Welcher Fluss fließt durch Prag?",
      ["Moldau", "Elbe", "March", "Donau"]),
    C("Who painted Las Meninas?",
      ["Diego Velázquez", "El Greco", "Francisco Goya", "Bartolomé Esteban Murillo"],
      "Kto namalował Panny dworskie, czyli Las Meninas?",
      ["Diego Velázquez", "El Greco", "Francisco Goya", "Bartolomé Esteban Murillo"],
      "Wer malte Las Meninas?",
      ["Diego Velázquez", "El Greco", "Francisco Goya", "Bartolomé Esteban Murillo"]),
    C("What is the approximate value of the Planck constant?",
      ["6.626 x 10^-34 J s", "6.022 x 10^23 /mol", "1.602 x 10^-19 C", "3.00 x 10^8 m/s"],
      "Ile wynosi w przybliżeniu stała Plancka?",
      ["6.626 x 10^-34 J s", "6.022 x 10^23 /mol", "1.602 x 10^-19 C", "3.00 x 10^8 m/s"],
      "Wie groß ist ungefähr das Plancksche Wirkungsquantum?",
      ["6.626 x 10^-34 J s", "6.022 x 10^23 /mol", "1.602 x 10^-19 C", "3.00 x 10^8 m/s"]),
    C("What is the capital of Burkina Faso?",
      ["Ouagadougou", "Bamako", "Niamey", "Accra"],
      "Jaka jest stolica Burkina Faso?",
      ["Wagadugu", "Bamako", "Niamej", "Akra"],
      "Was ist die Hauptstadt von Burkina Faso?",
      ["Ouagadougou", "Bamako", "Niamey", "Accra"]),
]

L13 = [
    C("In which year was the Union of Lublin concluded?",
      ["1569", "1385", "1413", "1791"],
      "W którym roku zawarto unię lubelską?",
      ["1569", "1385", "1413", "1791"],
      "In welchem Jahr wurde die Lubliner Union geschlossen?",
      ["1569", "1385", "1413", "1791"]),
    C("Who formulated the exclusion principle that no two electrons in an atom can share the same set of quantum numbers?",
      ["Wolfgang Pauli", "Paul Dirac", "Enrico Fermi", "Arnold Sommerfeld"],
      "Kto sformułował zakaz, według którego dwa elektrony w atomie nie mogą mieć tego samego zestawu liczb kwantowych?",
      ["Wolfgang Pauli", "Paul Dirac", "Enrico Fermi", "Arnold Sommerfeld"],
      "Wer formulierte das Ausschlussprinzip, wonach zwei Elektronen in einem Atom nicht dieselben Quantenzahlen haben dürfen?",
      ["Wolfgang Pauli", "Paul Dirac", "Enrico Fermi", "Arnold Sommerfeld"]),
    C("Who composed the opera Jenůfa?",
      ["Leoš Janáček", "Antonín Dvořák", "Bedřich Smetana", "Béla Bartók"],
      "Kto skomponował operę Jenůfa?",
      ["Leoš Janáček", "Antonín Dvořák", "Bedřich Smetana", "Béla Bartók"],
      "Wer komponierte die Oper Jenůfa?",
      ["Leoš Janáček", "Antonín Dvořák", "Bedřich Smetana", "Béla Bartók"]),
    C("The Defenestration of Prague in 1618 helped trigger which war?",
      ["Thirty Years' War", "Seven Years' War", "Hussite Wars", "War of the Austrian Succession"],
      "Defenestracja praska z 1618 roku przyczyniła się do wybuchu której wojny?",
      ["wojna trzydziestoletnia", "wojna siedmioletnia", "wojny husyckie", "wojna o sukcesję austriacką"],
      "Der Prager Fenstersturz von 1618 löste welchen Krieg mit aus?",
      ["Dreißigjähriger Krieg", "Siebenjähriger Krieg", "Hussitenkriege", "Österreichischer Erbfolgekrieg"]),
    C("What is the oxidation state of manganese in potassium permanganate, KMnO4?",
      ["+7", "+4", "+2", "+6"],
      "Jaki jest stopień utlenienia manganu w nadmanganianie potasu, KMnO4?",
      ["+7", "+4", "+2", "+6"],
      "Welche Oxidationszahl hat Mangan in Kaliumpermanganat, KMnO4?",
      ["+7", "+4", "+2", "+6"]),
    C("Who wrote The Phenomenology of Spirit?",
      ["Georg Wilhelm Friedrich Hegel", "Immanuel Kant", "Friedrich Schelling", "Johann Gottlieb Fichte"],
      "Kto napisał Fenomenologię ducha?",
      ["Georg Wilhelm Friedrich Hegel", "Immanuel Kant", "Friedrich Schelling", "Johann Gottlieb Fichte"],
      "Wer schrieb die Phänomenologie des Geistes?",
      ["Georg Wilhelm Friedrich Hegel", "Immanuel Kant", "Friedrich Schelling", "Johann Gottlieb Fichte"]),
    C("Which artist painted the Isenheim Altarpiece?",
      ["Matthias Grünewald", "Albrecht Dürer", "Lucas Cranach the Elder", "Hans Holbein the Younger"],
      "Który artysta namalował Ołtarz z Isenheim?",
      ["Matthias Grünewald", "Albrecht Dürer", "Lucas Cranach starszy", "Hans Holbein młodszy"],
      "Welcher Künstler malte den Isenheimer Altar?",
      ["Matthias Grünewald", "Albrecht Dürer", "Lucas Cranach der Ältere", "Hans Holbein der Jüngere"]),
    C("The Banach-Tarski paradox belongs primarily to which field of mathematics?",
      ["Set theory", "Number theory", "Surface topology", "Graph theory"],
      "Paradoks Banacha-Tarskiego należy przede wszystkim do której dziedziny matematyki?",
      ["teoria mnogości", "teoria liczb", "topologia powierzchni", "teoria grafów"],
      "Das Banach-Tarski-Paradoxon gehört vor allem zu welchem Gebiet der Mathematik?",
      ["Mengenlehre", "Zahlentheorie", "Flächentopologie", "Graphentheorie"]),
    C("Albert Einstein's Nobel Prize in Physics was awarded for work on which phenomenon?",
      ["The photoelectric effect", "Special relativity", "General relativity", "Brownian motion alone"],
      "Nagroda Nobla Einsteina w dziedzinie fizyki została przyznana za prace nad którym zjawiskiem?",
      ["efekt fotoelektryczny", "szczególna teoria względności", "ogólna teoria względności", "wyłącznie ruchy Browna"],
      "Den Nobelpreis für Physik erhielt Einstein für Arbeiten zu welchem Phänomen?",
      ["Photoeffekt", "spezielle Relativitätstheorie", "allgemeine Relativitätstheorie", "allein Brownsche Bewegung"]),
    C("In which present-day country was Béla Bartók born?",
      ["Romania", "Hungary", "Slovakia", "Austria"],
      "Béla Bartók urodził się na terenie którego dzisiejszego państwa?",
      ["Rumunia", "Węgry", "Słowacja", "Austria"],
      "In welchem heutigen Staat wurde Béla Bartók geboren?",
      ["Rumänien", "Ungarn", "Slowakei", "Österreich"]),
    C("In which year was the Treaty of Brest-Litovsk signed?",
      ["1918", "1917", "1919", "1921"],
      "W którym roku podpisano traktat brzeski?",
      ["1918", "1917", "1919", "1921"],
      "In welchem Jahr wurde der Vertrag von Brest-Litowsk unterzeichnet?",
      ["1918", "1917", "1919", "1921"]),
    C("Which amino acid has a thiol, or sulfhydryl, side chain?",
      ["Cysteine", "Methionine", "Serine", "Threonine"],
      "Który aminokwas zawiera łańcuch boczny tiolowy, czyli sulfhydrylowy?",
      ["cysteina", "metionina", "seryna", "treonina"],
      "Welche Aminosäure trägt eine Thiol- bzw. Sulfhydrylgruppe in der Seitenkette?",
      ["Cystein", "Methionin", "Serin", "Threonin"]),
    C("Who wrote The Praise of Folly?",
      ["Erasmus of Rotterdam", "Thomas More", "François Rabelais", "Michel de Montaigne"],
      "Kto napisał Pochwałę głupoty?",
      ["Erazm z Rotterdamu", "Tomasz Morus", "François Rabelais", "Michel de Montaigne"],
      "Wer schrieb Das Lob der Torheit?",
      ["Erasmus von Rotterdam", "Thomas Morus", "François Rabelais", "Michel de Montaigne"]),
    C("The Carlsbad Decrees of 1819 were issued under the influence of which Austrian statesman?",
      ["Klemens von Metternich", "Felix zu Schwarzenberg", "Wenzel Anton von Kaunitz", "Johann Philipp Stadion"],
      "Dekrety karlsbadzkie z 1819 roku wydano pod wpływem którego austriackiego męża stanu?",
      ["Klemens von Metternich", "Felix zu Schwarzenberg", "Wenzel Anton von Kaunitz", "Johann Philipp Stadion"],
      "Die Karlsbader Beschlüsse von 1819 entstanden unter dem Einfluss welchen österreichischen Staatsmanns?",
      ["Klemens von Metternich", "Felix zu Schwarzenberg", "Wenzel Anton von Kaunitz", "Johann Philipp Stadion"]),
    C("The historic Skoda Works were based in which Bohemian city?",
      ["Pilsen", "Brno", "Ostrava", "Liberec"],
      "W którym czeskim mieście powstały historyczne zakłady Škoda?",
      ["Pilzno", "Brno", "Ostrawa", "Liberec"],
      "In welcher böhmischen Stadt entstanden die Škoda-Werke?",
      ["Pilsen", "Brünn", "Ostrau", "Reichenberg"]),
    C("Who painted The Arnolfini Portrait?",
      ["Jan van Eyck", "Rogier van der Weyden", "Robert Campin", "Hans Memling"],
      "Kto namalował Portret Arnolfinich?",
      ["Jan van Eyck", "Rogier van der Weyden", "Robert Campin", "Hans Memling"],
      "Wer malte das Arnolfini-Porträt?",
      ["Jan van Eyck", "Rogier van der Weyden", "Robert Campin", "Hans Memling"]),
    C("Which Japanese physicist predicted the existence of the pion?",
      ["Hideki Yukawa", "Shinichirō Tomonaga", "Yoichiro Nambu", "Masatoshi Koshiba"],
      "Który japoński fizyk przewidział istnienie pionu?",
      ["Hideki Yukawa", "Shinichirō Tomonaga", "Yoichiro Nambu", "Masatoshi Koshiba"],
      "Welcher japanische Physiker sagte das Pion voraus?",
      ["Hideki Yukawa", "Shinichirō Tomonaga", "Yoichiro Nambu", "Masatoshi Koshiba"]),
    C("In which year was the Polish Constitution of 3 May adopted?",
      ["1791", "1793", "1772", "1815"],
      "W którym roku uchwalono Konstytucję 3 maja?",
      ["1791", "1793", "1772", "1815"],
      "In welchem Jahr wurde die polnische Verfassung vom 3. Mai verabschiedet?",
      ["1791", "1793", "1772", "1815"]),
    C("Who wrote the drama Woyzeck?",
      ["Georg Büchner", "Heinrich von Kleist", "Friedrich Schiller", "Gotthold Ephraim Lessing"],
      "Kto napisał dramat Woyzeck?",
      ["Georg Büchner", "Heinrich von Kleist", "Friedrich Schiller", "Gotthold Ephraim Lessing"],
      "Wer schrieb das Drama Woyzeck?",
      ["Georg Büchner", "Heinrich von Kleist", "Friedrich Schiller", "Gotthold Ephraim Lessing"]),
    C("What is the coordination number of the central atom in the ion [Fe(CN)6]4-?",
      ["6", "4", "2", "8"],
      "Jaka jest liczba koordynacyjna atomu centralnego w jonie [Fe(CN)6]4-?",
      ["6", "4", "2", "8"],
      "Welche Koordinationszahl hat das Zentralatom in [Fe(CN)6]4-?",
      ["6", "4", "2", "8"]),
    C("The Battle of Königgrätz, or Sadowa, in 1866 was a decisive victory for which state?",
      ["Prussia", "Austria", "France", "Russia"],
      "Bitwa pod Sadową, zwana też bitwą pod Königgrätz, w 1866 roku była decydującym zwycięstwem którego państwa?",
      ["Prusy", "Austria", "Francja", "Rosja"],
      "Die Schlacht bei Königgrätz 1866 war ein entscheidender Sieg welchen Staates?",
      ["Preußen", "Österreich", "Frankreich", "Russland"]),
    C("Who wrote the Tractatus Logico-Philosophicus?",
      ["Ludwig Wittgenstein", "Bertrand Russell", "Gottlob Frege", "Rudolf Carnap"],
      "Kto jest autorem Traktatu logiczno-filozoficznego?",
      ["Ludwig Wittgenstein", "Bertrand Russell", "Gottlob Frege", "Rudolf Carnap"],
      "Wer ist der Autor des Tractatus logico-philosophicus?",
      ["Ludwig Wittgenstein", "Bertrand Russell", "Gottlob Frege", "Rudolf Carnap"]),
    C("Which strait separates the islands of Sumatra and Java?",
      ["Sunda Strait", "Strait of Malacca", "Lombok Strait", "Makassar Strait"],
      "Która cieśnina oddziela Sumatrę od Jawy?",
      ["Cieśnina Sundajska", "Cieśnina Malakka", "Cieśnina Lombok", "Cieśnina Makasarska"],
      "Welche Meerenge trennt Sumatra und Java?",
      ["Sundastraße", "Straße von Malakka", "Lombokstraße", "Makassarstraße"]),
    C("Who composed the opera Bluebeard's Castle?",
      ["Béla Bartók", "Zoltán Kodály", "Franz Liszt", "Ernst von Dohnányi"],
      "Kto skomponował operę Zamek Sinobrodego?",
      ["Béla Bartók", "Zoltán Kodály", "Franz Liszt", "Ernst von Dohnányi"],
      "Wer komponierte die Oper Herzog Blaubarts Burg?",
      ["Béla Bartók", "Zoltán Kodály", "Franz Liszt", "Ernst von Dohnányi"]),
    C("The Schwarzschild radius is associated chiefly with which objects?",
      ["Black holes", "Neutron stars", "White dwarfs", "Quasars alone"],
      "Promień Schwarzschilda wiąże się przede wszystkim z jakimi obiektami?",
      ["czarne dziury", "gwiazdy neutronowe", "białe karły", "wyłącznie kwazary"],
      "Der Schwarzschild-Radius wird vor allem mit welchen Objekten verbunden?",
      ["schwarze Löcher", "Neutronensterne", "weiße Zwerge", "allein Quasare"]),
    C("Who first synthesized urea from ammonium cyanate in 1828?",
      ["Friedrich Wöhler", "Justus von Liebig", "Jöns Jacob Berzelius", "Hermann Kolbe"],
      "Kto w 1828 roku po raz pierwszy zsyntetyzował mocznik z cyjanianu amonu?",
      ["Friedrich Wöhler", "Justus von Liebig", "Jöns Jacob Berzelius", "Hermann Kolbe"],
      "Wer synthetisierte 1828 als Erster Harnstoff aus Ammoniumcyanat?",
      ["Friedrich Wöhler", "Justus von Liebig", "Jöns Jacob Berzelius", "Hermann Kolbe"]),
]

L14 = [
    C("Who was the last Jagiellonian king of Poland?",
      ["Sigismund II Augustus", "Sigismund I the Old", "Casimir IV Jagiellon", "John I Albert"],
      "Kto był ostatnim Jagiellonem na polskim tronie?",
      ["Zygmunt II August", "Zygmunt I Stary", "Kazimierz IV Jagiellończyk", "Jan I Olbracht"],
      "Wer war der letzte Jagiellonenkönig von Polen?",
      ["Sigismund II. August", "Sigismund I. der Alte", "Kasimir IV. Andreas", "Johann I. Albrecht"]),
    C("The Raman effect, for which C. V. Raman won the 1930 Nobel Prize, is a form of what?",
      ["Inelastic scattering of light", "Elastic scattering of X-rays", "Nuclear magnetic resonance", "Photoelectric emission"],
      "Efekt Ramana, za który C. V. Raman otrzymał Nobla w 1930 roku, jest postacią czego?",
      ["nieelastycznego rozpraszania światła", "sprężystego rozpraszania promieni X", "magnetycznego rezonansu jądrowego", "emisji fotoelektrycznej"],
      "Der Raman-Effekt, für den C. V. Raman 1930 den Nobelpreis erhielt, ist eine Form von?",
      ["inelastischer Lichtstreuung", "elastischer Röntgenstreuung", "kernmagnetischer Resonanz", "photoelektrischer Emission"]),
    C("Who painted the fresco cycle in the Scrovegni Chapel in Padua?",
      ["Giotto", "Cimabue", "Duccio", "Masaccio"],
      "Kto namalował cykl fresków w kaplicy Scrovegnich w Padwie?",
      ["Giotto", "Cimabue", "Duccio", "Masaccio"],
      "Wer malte den Freskenzyklus der Scrovegni-Kapelle in Padua?",
      ["Giotto", "Cimabue", "Duccio", "Masaccio"]),
    C("What is the name of the 1356 edict by which Charles IV regulated imperial elections?",
      ["Golden Bull", "Pragmatic Sanction", "Peace of Augsburg", "Capitulation of Wittenberg"],
      "Jak nazywa się edykt z 1356 roku, w którym Karol IV uregulował wybór cesarza?",
      ["Złota Bulla", "sankcja pragmatyczna", "pokój augsburski", "kapitulacja wittenberska"],
      "Wie heißt das Edikt von 1356, mit dem Karl IV. die Kaiserwahl regelte?",
      ["Goldene Bulle", "Pragmatische Sanktion", "Augsburger Religionsfrieden", "Wittenberger Kapitulation"]),
    C("Who wrote The Man Without Qualities?",
      ["Robert Musil", "Hermann Broch", "Thomas Bernhard", "Elias Canetti"],
      "Kto napisał Człowieka bez właściwości?",
      ["Robert Musil", "Hermann Broch", "Thomas Bernhard", "Elias Canetti"],
      "Wer schrieb Der Mann ohne Eigenschaften?",
      ["Robert Musil", "Hermann Broch", "Thomas Bernhard", "Elias Canetti"]),
    C("Which isotope is most commonly used in PET medical imaging?",
      ["Fluorine-18", "Iodine-131", "Cobalt-60", "Technetium-99m"],
      "Który izotop najczęściej stosuje się w obrazowaniu PET?",
      ["fluor-18", "jod-131", "kobalt-60", "technet-99m"],
      "Welches Isotop wird in der PET-Bildgebung am häufigsten verwendet?",
      ["Fluor-18", "Iod-131", "Cobalt-60", "Technetium-99m"]),
    C("Who composed the opera Lulu?",
      ["Alban Berg", "Arnold Schönberg", "Anton Webern", "Kurt Weill"],
      "Kto skomponował operę Lulu?",
      ["Alban Berg", "Arnold Schönberg", "Anton Webern", "Kurt Weill"],
      "Wer komponierte die Oper Lulu?",
      ["Alban Berg", "Arnold Schönberg", "Anton Webern", "Kurt Weill"]),
    C("The Grodno Sejm of 1793 is associated with which partition of Poland?",
      ["The Second Partition", "The First Partition", "The Third Partition", "None of the partitions"],
      "Sejm grodzieński z 1793 roku wiąże się z którym rozbiorem Polski?",
      ["II rozbiorem", "I rozbiorem", "III rozbiorem", "z żadnym rozbiorem"],
      "Der Grodnoer Sejm von 1793 steht im Zusammenhang mit welcher Teilung Polens?",
      ["der Zweiten Teilung", "der Ersten Teilung", "der Dritten Teilung", "keiner Teilung"]),
    C("Which conjecture did Grigori Perelman prove in the early 2000s?",
      ["Poincaré conjecture", "Goldbach conjecture", "Riemann hypothesis", "Hodge conjecture"],
      "Którą hipotezę udowodnił Grigorij Perelman na początku XXI wieku?",
      ["hipoteza Poincarégo", "hipoteza Goldbacha", "hipoteza Riemanna", "hipoteza Hodge'a"],
      "Welche Vermutung bewies Grigori Perelman Anfang der 2000er Jahre?",
      ["Poincaré-Vermutung", "Goldbachsche Vermutung", "Riemannsche Vermutung", "Hodge-Vermutung"]),
    C("Which philosopher wrote Either/Or and Fear and Trembling?",
      ["Søren Kierkegaard", "Friedrich Nietzsche", "Arthur Schopenhauer", "Georg Wilhelm Friedrich Hegel"],
      "Który filozof napisał Albo-albo oraz Bojaźń i drżenie?",
      ["Søren Kierkegaard", "Friedrich Nietzsche", "Arthur Schopenhauer", "Georg Wilhelm Friedrich Hegel"],
      "Welcher Philosoph schrieb Entweder-Oder und Furcht und Zittern?",
      ["Søren Kierkegaard", "Friedrich Nietzsche", "Arthur Schopenhauer", "Georg Wilhelm Friedrich Hegel"]),
    C("The mineral cinnabar is the chief ore of which element?",
      ["Mercury", "Lead", "Antimony", "Arsenic"],
      "Cynober jest główną rudą którego pierwiastka?",
      ["rtęci", "ołowiu", "antymonu", "arsenu"],
      "Zinnober ist das wichtigste Erz welches Elements?",
      ["Quecksilber", "Blei", "Antimon", "Arsen"]),
    C("The First Defenestration of Prague in 1419 is associated with the outbreak of which wars?",
      ["Hussite Wars", "Thirty Years' War", "Schmalkaldic War", "War of the Spanish Succession"],
      "Pierwsza defenestracja praska z 1419 roku wiąże się z wybuchem których wojen?",
      ["wojny husyckie", "wojna trzydziestoletnia", "wojna szmalkaldzka", "wojna o sukcesję hiszpańską"],
      "Der erste Prager Fenstersturz von 1419 steht am Beginn welcher Kriege?",
      ["Hussitenkriege", "Dreißigjähriger Krieg", "Schmalkaldischer Krieg", "Spanischer Erbfolgekrieg"]),
    C("Which chemist isolated potassium and sodium by electrolysis in 1807?",
      ["Humphry Davy", "Jöns Jacob Berzelius", "Joseph Louis Gay-Lussac", "Michael Faraday"],
      "Który chemik wyodrębnił potas i sód na drodze elektrolizy w 1807 roku?",
      ["Humphry Davy", "Jöns Jacob Berzelius", "Joseph Louis Gay-Lussac", "Michael Faraday"],
      "Welcher Chemiker isolierte 1807 Kalium und Natrium durch Elektrolyse?",
      ["Humphry Davy", "Jöns Jacob Berzelius", "Joseph Louis Gay-Lussac", "Michael Faraday"]),
    C("The city of Kosice lies today in which country?",
      ["Slovakia", "Hungary", "Ukraine", "Czech Republic"],
      "Miasto Koszyce leży dziś w którym państwie?",
      ["Słowacja", "Węgry", "Ukraina", "Czechy"],
      "In welchem heutigen Staat liegt Kaschau, also Košice?",
      ["Slowakei", "Ungarn", "Ukraine", "Tschechien"]),
    C("Who painted The Burial of the Count of Orgaz?",
      ["El Greco", "Diego Velázquez", "Francisco de Zurbarán", "Jusepe de Ribera"],
      "Kto namalował Pogrzeb hrabiego Orgaza?",
      ["El Greco", "Diego Velázquez", "Francisco de Zurbarán", "Jusepe de Ribera"],
      "Wer malte Das Begräbnis des Grafen von Orgaz?",
      ["El Greco", "Diego Velázquez", "Francisco de Zurbarán", "Jusepe de Ribera"]),
    C("The Meissner effect is the expulsion of magnetic fields from what?",
      ["Superconductors", "Ferromagnets", "Plasmas", "Dielectrics"],
      "Efekt Meissnera to wypychanie pola magnetycznego z czego?",
      ["nadprzewodników", "ferromagnetyków", "plazmy", "dielektryków"],
      "Der Meißner-Ochsenfeld-Effekt ist die Verdrängung magnetischer Felder aus?",
      ["Supraleitern", "Ferromagneten", "Plasmen", "Dielektrika"]),
    C("Who wrote the novel Berlin Alexanderplatz?",
      ["Alfred Döblin", "Hans Fallada", "Erich Kästner", "Heinrich Mann"],
      "Kto napisał powieść Berlin Alexanderplatz?",
      ["Alfred Döblin", "Hans Fallada", "Erich Kästner", "Heinrich Mann"],
      "Wer schrieb den Roman Berlin Alexanderplatz?",
      ["Alfred Döblin", "Hans Fallada", "Erich Kästner", "Heinrich Mann"]),
    C("In organic chemistry, the Diels-Alder reaction is a cycloaddition between a diene and what?",
      ["A dienophile", "A Grignard reagent", "An enolate", "A carbene"],
      "Reakcja Dielsa-Aldera to cykloaddycja dienu do czego?",
      ["dienofila", "odczynnika Grignarda", "enolanu", "karbenu"],
      "Die Diels-Alder-Reaktion ist eine Cycloaddition zwischen einem Dien und?",
      ["einem Dienophil", "einem Grignard-Reagenz", "einem Enolat", "einem Carben"]),
    C("Which king of Bohemia, also Holy Roman Emperor, founded Charles University in Prague?",
      ["Charles IV", "Ottokar II", "Wenceslaus IV", "Rudolf II"],
      "Który król Czech, zarazem cesarz rzymski, założył Uniwersytet Karola w Pradze?",
      ["Karol IV", "Przemysł Ottokar II", "Wacław IV", "Rudolf II"],
      "Welcher böhmische König und römisch-deutsche Kaiser gründete die Karlsuniversität in Prag?",
      ["Karl IV.", "Ottokar II.", "Wenzel IV.", "Rudolf II."]),
    C("What is the SI unit of magnetic flux?",
      ["Weber", "Tesla", "Henry", "Gauss"],
      "Jaka jest jednostka SI strumienia magnetycznego?",
      ["weber", "tesla", "henry", "gauss"],
      "Was ist die SI-Einheit des magnetischen Flusses?",
      ["Weber", "Tesla", "Henry", "Gauss"]),
    C("Who received the 1905 Nobel Peace Prize, the first woman so honoured?",
      ["Bertha von Suttner", "Jane Addams", "Mother Teresa", "Emily Greene Balch"],
      "Kto otrzymał Pokojową Nagrodę Nobla w 1905 roku jako pierwsza kobieta?",
      ["Bertha von Suttner", "Jane Addams", "Matka Teresa", "Emily Greene Balch"],
      "Wer erhielt 1905 als erste Frau den Friedensnobelpreis?",
      ["Bertha von Suttner", "Jane Addams", "Mutter Teresa", "Emily Greene Balch"]),
    C("The Codex Gigas, also called the Devil's Bible, is kept chiefly in which city?",
      ["Stockholm", "Prague", "Vienna", "Krakow"],
      "Kodeks Gigas, zwany Biblią Diabła, przechowywany jest głównie w którym mieście?",
      ["Sztokholm", "Praga", "Wiedeń", "Kraków"],
      "Der Codex Gigas, auch Teufelsbibel genannt, wird vor allem in welcher Stadt aufbewahrt?",
      ["Stockholm", "Prag", "Wien", "Krakau"]),
    C("Who composed the symphony nicknamed The Titan?",
      ["Gustav Mahler", "Anton Bruckner", "Richard Strauss", "Jean Sibelius"],
      "Kto skomponował symfonię zwaną Tytanem?",
      ["Gustav Mahler", "Anton Bruckner", "Richard Strauss", "Jean Sibelius"],
      "Wer komponierte die Sinfonie mit dem Beinamen Der Titan?",
      ["Gustav Mahler", "Anton Bruckner", "Richard Strauss", "Jean Sibelius"]),
    C("Which Habsburg emperor issued the Pragmatic Sanction of 1713 to secure the succession of Maria Theresa?",
      ["Charles VI", "Leopold I", "Charles V", "Joseph I"],
      "Sankcję pragmatyczną z 1713 roku wydał który cesarz Habsburg, by zapewnić sukcesję Marii Teresie?",
      ["Karol VI", "Leopold I", "Karol V", "Józef I"],
      "Die Pragmatische Sanktion von 1713 erließ welcher Habsburgerkaiser, um die Thronfolge Maria Theresias zu sichern?",
      ["Karl VI.", "Leopold I.", "Karl V.", "Joseph I."]),
    C("Polish notation, or Lukasiewicz notation, belongs chiefly to which discipline?",
      ["Logic", "Astronomy", "Crystallography", "Phonetics"],
      "Notacja Łukasiewicza, zwana też notacją polską, wiąże się z którą dziedziną?",
      ["logika", "astronomia", "krystalografia", "fonetyka"],
      "Die Łukasiewicz-Notation, auch polnische Notation, gehört zu welchem Gebiet?",
      ["Logik", "Astronomie", "Kristallographie", "Phonetik"]),
    C("Who formulated the heat theorem that became a foundation of the third law of thermodynamics?",
      ["Walther Nernst", "Max Planck", "Rudolf Clausius", "Lord Kelvin"],
      "Kto sformułował twierdzenie cieplne, które stało się podstawą trzeciej zasady termodynamiki?",
      ["Walther Nernst", "Max Planck", "Rudolf Clausius", "lord Kelvin"],
      "Wer formulierte das Wärmetheorem, das zur Grundlage des dritten Hauptsatzes der Thermodynamik wurde?",
      ["Walther Nernst", "Max Planck", "Rudolf Clausius", "Lord Kelvin"]),
]

L15 = [
    C("In which year did Louis I of Hungary grant the Privilege of Kosice to the Polish nobility?",
      ["1374", "1355", "1386", "1413"],
      "W którym roku Ludwik Węgierski nadał szlachcie przywilej koszycki?",
      ["1374", "1355", "1386", "1413"],
      "In welchem Jahr gewährte Ludwig I. von Ungarn der polnischen Szlachta das Kaschauer Privileg?",
      ["1374", "1355", "1386", "1413"]),
    C("The astronomer Johannes Hevelius, famous for selenography, worked chiefly in which city?",
      ["Gdansk", "Krakow", "Torun", "Wroclaw"],
      "Jan Heweliusz, słynny selenograf, działał przede wszystkim w którym mieście?",
      ["Gdańsk", "Kraków", "Toruń", "Wrocław"],
      "Johannes Hevelius, berühmt für seine Selenographie, wirkte vor allem in welcher Stadt?",
      ["Danzig", "Krakau", "Thorn", "Breslau"]),
    C("Which pair of mathematicians independently proved the prime number theorem in 1896?",
      ["Jacques Hadamard and Charles Jean de la Vallée Poussin", "David Hilbert and Hermann Minkowski", "G. H. Hardy and John Edensor Littlewood", "Émile Borel and Henri Lebesgue"],
      "Która para matematyków niezależnie udowodniła w 1896 roku twierdzenie o liczbach pierwszych?",
      ["Jacques Hadamard i Charles Jean de la Vallée Poussin", "David Hilbert i Hermann Minkowski", "G. H. Hardy i John Edensor Littlewood", "Émile Borel i Henri Lebesgue"],
      "Welches Mathematikergespann bewies 1896 unabhängig voneinander den Primzahlsatz?",
      ["Jacques Hadamard und Charles Jean de la Vallée Poussin", "David Hilbert und Hermann Minkowski", "G. H. Hardy und John Edensor Littlewood", "Émile Borel und Henri Lebesgue"]),
    C("Who painted the Venetian canvas known as The Tempest, or La Tempesta?",
      ["Giorgione", "Titian", "Giovanni Bellini", "Tintoretto"],
      "Kto namalował weneckie płótno Burza, zwane też La Tempesta?",
      ["Giorgione", "Tycjan", "Giovanni Bellini", "Tintoretto"],
      "Wer malte das venezianische Bild Das Gewitter, auch La Tempesta?",
      ["Giorgione", "Tizian", "Giovanni Bellini", "Tintoretto"]),
    C("What is the name of the 1466 peace that ended the Thirteen Years' War between Poland and the Teutonic Order?",
      ["Second Peace of Thorn", "First Peace of Thorn", "Peace of Melno", "Peace of Krakow"],
      "Jak nazywa się pokój z 1466 roku, który zakończył wojnę trzynastoletnią między Polską a Zakonem Krzyżackim?",
      ["II pokój toruński", "I pokój toruński", "pokój mełneński", "pokój krakowski"],
      "Wie heißt der Frieden von 1466, der den Dreizehnjährigen Krieg zwischen Polen und dem Deutschen Orden beendete?",
      ["Zweiter Frieden von Thorn", "Erster Frieden von Thorn", "Frieden vom Melnosee", "Krakauer Frieden"]),
    C("Who shared the 2001 Nobel Prize in Physics with Cornell and Wieman for Bose-Einstein condensation?",
      ["Wolfgang Ketterle", "Steven Chu", "Claude Cohen-Tannoudji", "Theodor W. Hänsch"],
      "Kto wraz z Cornellem i Wiemanem otrzymał Nobla z fizyki w 2001 roku za kondensat Bosego-Einsteina?",
      ["Wolfgang Ketterle", "Steven Chu", "Claude Cohen-Tannoudji", "Theodor W. Hänsch"],
      "Wer teilte sich 2001 den Physik-Nobelpreis mit Cornell und Wieman für Bose-Einstein-Kondensation?",
      ["Wolfgang Ketterle", "Steven Chu", "Claude Cohen-Tannoudji", "Theodor W. Hänsch"]),
    C("Who composed the opera Julietta?",
      ["Bohuslav Martinů", "Leoš Janáček", "Bedřich Smetana", "Josef Suk"],
      "Kto skomponował operę Julietta?",
      ["Bohuslav Martinů", "Leoš Janáček", "Bedřich Smetana", "Josef Suk"],
      "Wer komponierte die Oper Julietta?",
      ["Bohuslav Martinů", "Leoš Janáček", "Bedřich Smetana", "Josef Suk"]),
    C("Who wrote The Star of Redemption?",
      ["Franz Rosenzweig", "Walter Benjamin", "Gershom Scholem", "Hermann Cohen"],
      "Kto napisał Gwiazdę zbawienia?",
      ["Franz Rosenzweig", "Walter Benjamin", "Gershom Scholem", "Hermann Cohen"],
      "Wer schrieb Der Stern der Erlösung?",
      ["Franz Rosenzweig", "Walter Benjamin", "Gershom Scholem", "Hermann Cohen"]),
    C("Which isotope of iodine is the only stable one that occurs naturally in significant amounts?",
      ["I-127", "I-129", "I-131", "I-125"],
      "Który izotop jodu jest jedynym trwałym, występującym naturalnie w znaczących ilościach?",
      ["I-127", "I-129", "I-131", "I-125"],
      "Welches Iodisotop ist das einzige stabile, das natürlich in nennenswerten Mengen vorkommt?",
      ["I-127", "I-129", "I-131", "I-125"]),
    C("Which Polish-Hungarian king died at the Battle of Varna in 1444?",
      ["Władysław III", "Casimir IV", "Louis II", "Sigismund I"],
      "W bitwie pod Warną w 1444 roku zginął który król polsko-węgierski?",
      ["Władysław III", "Kazimierz IV", "Ludwik II", "Zygmunt I"],
      "In der Schlacht bei Warna 1444 fiel welcher polnisch-ungarische König?",
      ["Władysław III.", "Kasimir IV.", "Ludwig II.", "Sigismund I."]),
    C("Who isolated the element fluorine in 1886?",
      ["Henri Moissan", "Humphry Davy", "Carl Wilhelm Scheele", "Henri Becquerel"],
      "Kto wyodrębnił fluor w 1886 roku?",
      ["Henri Moissan", "Humphry Davy", "Carl Wilhelm Scheele", "Henri Becquerel"],
      "Wer isolierte 1886 das Element Fluor?",
      ["Henri Moissan", "Humphry Davy", "Carl Wilhelm Scheele", "Henri Becquerel"]),
    C("The Adoration of the Mystic Lamb is the central panel of which altarpiece?",
      ["Ghent Altarpiece", "Isenheim Altarpiece", "Portinari Altarpiece", "Merode Altarpiece"],
      "Pokłon Barankowi Mistycznemu to centralna część którego ołtarza?",
      ["Ołtarz Gandawski", "Ołtarz z Isenheim", "Ołtarz Portinarich", "Ołtarz Merode"],
      "Die Anbetung des Lammes ist das Mittelstück welches Altars?",
      ["Genter Altar", "Isenheimer Altar", "Portinari-Altar", "Merode-Altar"]),
    C("The Mohorovicic discontinuity, or Moho, was discovered by a scientist from which present-day country?",
      ["Croatia", "Slovenia", "Serbia", "Italy"],
      "Nieciągłość Mohorovičicia, czyli Moho, odkrył uczony pochodzący z terenu którego dzisiejszego państwa?",
      ["Chorwacja", "Słowenia", "Serbia", "Włochy"],
      "Die Mohorovičić-Diskontinuität, kurz Moho, entdeckte ein Wissenschaftler aus welchem heutigen Land?",
      ["Kroatien", "Slowenien", "Serbien", "Italien"]),
    C("The earliest known Polish chronicle, Gesta principum Polonorum, is attributed to whom?",
      ["Gallus Anonymous", "Wincenty Kadlubek", "Jan Dlugosz", "Cosmas of Prague"],
      "Najstarsza znana kronika polska, Gesta principum Polonorum, przypisywana jest komu?",
      ["Gall Anonim", "Wincenty Kadłubek", "Jan Długosz", "Kosmas z Pragi"],
      "Die älteste bekannte polnische Chronik, Gesta principum Polonorum, wird wem zugeschrieben?",
      ["Gallus Anonymus", "Wincenty Kadłubek", "Jan Długosz", "Cosmas von Prag"]),
    C("Which Dutch physicist received the 1902 Nobel Prize for work on the Zeeman effect and gave the Lorentz transformations their modern form?",
      ["Hendrik Lorentz", "Pieter Zeeman", "Heike Kamerlingh Onnes", "Johannes Diderik van der Waals"],
      "Który holenderski fizyk otrzymał w 1902 roku Nobla za prace nad efektem Zeemana i nadał transformacjom noszącym jego imię nowożytną postać?",
      ["Hendrik Lorentz", "Pieter Zeeman", "Heike Kamerlingh Onnes", "Johannes Diderik van der Waals"],
      "Welcher niederländische Physiker erhielt 1902 den Nobelpreis für Arbeiten zum Zeeman-Effekt und gab den Lorentz-Transformationen ihre moderne Form?",
      ["Hendrik Lorentz", "Pieter Zeeman", "Heike Kamerlingh Onnes", "Johannes Diderik van der Waals"]),
    C("What was the name of Matthias Corvinus's famous library in Buda?",
      ["Bibliotheca Corviniana", "Bibliotheca Palatina", "Bibliotheca Apostolica", "Bibliotheca Ambrosiana"],
      "Słynna biblioteka Macieja Korwina na Budzie nosiła nazwę?",
      ["Bibliotheca Corviniana", "Bibliotheca Palatina", "Bibliotheca Apostolica", "Bibliotheca Ambrosiana"],
      "Die berühmte Bibliothek von Matthias Corvinus in Buda hieß?",
      ["Bibliotheca Corviniana", "Bibliotheca Palatina", "Bibliotheca Apostolica", "Bibliotheca Ambrosiana"]),
    C("Who composed the oratorio Christ on the Mount of Olives?",
      ["Ludwig van Beethoven", "Joseph Haydn", "Felix Mendelssohn", "Franz Liszt"],
      "Kto skomponował oratorium Chrystus na Górze Oliwnej?",
      ["Ludwig van Beethoven", "Joseph Haydn", "Felix Mendelssohn", "Franz Liszt"],
      "Wer komponierte das Oratorium Christus am Ölberge?",
      ["Ludwig van Beethoven", "Joseph Haydn", "Felix Mendelssohn", "Franz Liszt"]),
    C("The reaction of a carbonyl compound with a phosphorus ylide to form an alkene is named after which chemist?",
      ["Georg Wittig", "Victor Grignard", "Otto Diels", "Hermann Staudinger"],
      "Reakcję związku karbonylowego z ilidem fosforu, dającą alken, nazwano od którego chemika?",
      ["Georg Wittig", "Victor Grignard", "Otto Diels", "Hermann Staudinger"],
      "Die Reaktion einer Carbonylverbindung mit einem Phosphorylid zum Alken trägt den Namen welches Chemikers?",
      ["Georg Wittig", "Victor Grignard", "Otto Diels", "Hermann Staudinger"]),
    C("The Prussian Homage of 1525 was paid by Albrecht of Hohenzollern to which king of Poland?",
      ["Sigismund I the Old", "Sigismund II Augustus", "Casimir IV", "Stephen Bathory"],
      "Hołd pruski z 1525 roku Albrecht Hohenzollern złożył któremu królowi Polski?",
      ["Zygmuntowi I Staremu", "Zygmuntowi II Augustowi", "Kazimierzowi IV", "Stefanowi Batoremu"],
      "Die Preußische Huldigung von 1525 leistete Albrecht von Hohenzollern welchem polnischen König?",
      ["Sigismund I. dem Alten", "Sigismund II. August", "Kasimir IV.", "Stephan Báthory"]),
    C("Who wrote The Book of the City of Ladies?",
      ["Christine de Pizan", "Hildegard of Bingen", "Margery Kempe", "Marie de France"],
      "Kto napisała Księgę o mieście dam?",
      ["Christine de Pizan", "Hildegarda z Bingen", "Margery Kempe", "Marie de France"],
      "Wer schrieb Das Buch von der Stadt der Frauen?",
      ["Christine de Pizan", "Hildegard von Bingen", "Margery Kempe", "Marie de France"]),
    C("The CNO cycle converts hydrogen into helium using which elements as catalysts?",
      ["Carbon, nitrogen and oxygen", "Iron, nickel and cobalt", "Helium and lithium", "Uranium and thorium"],
      "Cykl CNO przekształca wodór w hel przy udziale których pierwiastków jako katalizatorów?",
      ["węgla, azotu i tlenu", "żelaza, niklu i kobaltu", "helu i litu", "uranu i toru"],
      "Der CNO-Zyklus wandelt Wasserstoff in Helium um und nutzt welche Elemente als Katalysatoren?",
      ["Kohlenstoff, Stickstoff und Sauerstoff", "Eisen, Nickel und Cobalt", "Helium und Lithium", "Uran und Thorium"]),
    C("The Chapel of the Holy Cross at Karlstejn Castle was decorated with panels attributed mainly to which court painter of Charles IV?",
      ["Master Theodoric", "Master of Vyssi Brod", "Peter Parler", "Veit Stoss"],
      "Kaplicę Świętego Krzyża na zamku Karlštejn ozdobiono tablicami przypisywanymi głównie któremu nadwornemu malarzowi Karola IV?",
      ["Mistrzowi Teodorykowi", "Mistrzowi z Vyšší Brod", "Piotrowi Parlerowi", "Witowi Stwoszowi"],
      "Die Heilig-Kreuz-Kapelle auf Burg Karlstein schmückte vor allem welcher Hofmaler Karls IV.?",
      ["Meister Theoderich", "Meister von Hohenfurth", "Peter Parler", "Veit Stoß"]),
    C("What is the name of the 1422 Polish-Teutonic peace that fixed the border near the Lithuanian coast?",
      ["Peace of Melno", "Second Peace of Thorn", "First Peace of Thorn", "Peace of Brest"],
      "Jak nazywa się polsko-krzyżacki pokój z 1422 roku, który ustalił granicę w rejonie wybrzeża litewskiego?",
      ["pokój mełneński", "II pokój toruński", "I pokój toruński", "pokój brzeski"],
      "Wie heißt der polnisch-deutschordensche Frieden von 1422, der die Grenze an der litauischen Küste festlegte?",
      ["Frieden vom Melnosee", "Zweiter Frieden von Thorn", "Erster Frieden von Thorn", "Frieden von Brest"]),
    C("Who experimentally detected the neutrino in 1956 and later received the 1995 Nobel Prize in Physics?",
      ["Frederick Reines", "Wolfgang Pauli", "Enrico Fermi", "Bruno Pontecorvo"],
      "Kto współodkrył neutrino w 1956 roku i otrzymał za to Nobla w 1995?",
      ["Frederick Reines", "Wolfgang Pauli", "Enrico Fermi", "Bruno Pontecorvo"],
      "Wer wies 1956 das Neutrino experimentell nach und erhielt dafür 1995 den Nobelpreis?",
      ["Frederick Reines", "Wolfgang Pauli", "Enrico Fermi", "Bruno Pontecorvo"]),
    C("Who wrote the novel The Sleepwalkers?",
      ["Hermann Broch", "Robert Musil", "Elias Canetti", "Alfred Döblin"],
      "Kto napisał powieść Lunatycy?",
      ["Hermann Broch", "Robert Musil", "Elias Canetti", "Alfred Döblin"],
      "Wer schrieb den Roman Die Schlafwandler?",
      ["Hermann Broch", "Robert Musil", "Elias Canetti", "Alfred Döblin"]),
    C("Kepler's supernova of 1604 appeared in which constellation?",
      ["Ophiuchus", "Cassiopeia", "Taurus", "Andromeda"],
      "Supernowa Keplera z 1604 roku pojawiła się w którym gwiazdozbiorze?",
      ["Wężownik", "Kasjopea", "Byk", "Andromeda"],
      "Keplers Supernova von 1604 erschien in welchem Sternbild?",
      ["Schlangenträger", "Kassiopeia", "Stier", "Andromeda"]),
]
