from qfmt import C

# Easy adult general knowledge — first rung, not children's riddles.
L1 = [
    C("Which city is the capital of Portugal?",
      ["Lisbon", "Porto", "Madrid", "Seville"],
      "Które miasto jest stolicą Portugalii?",
      ["Lizbona", "Porto", "Madryt", "Sewilla"],
      "Welche Stadt ist die Hauptstadt Portugals?",
      ["Lissabon", "Porto", "Madrid", "Sevilla"]),
    C("How many strings does a standard guitar usually have?",
      ["6", "4", "8", "12"],
      "Ile strun ma zwykle zwykła gitara?",
      ["6", "4", "8", "12"],
      "Wie viele Saiten hat eine normale Gitarre meist?",
      ["6", "4", "8", "12"]),
    C("Which ocean lies between Europe and North America?",
      ["Atlantic", "Pacific", "Indian", "Arctic"],
      "Który ocean leży między Europą a Ameryką Północną?",
      ["Atlantycki", "Spokojny", "Indyjski", "Arktyczny"],
      "Welcher Ozean liegt zwischen Europa und Nordamerika?",
      ["Atlantik", "Pazifik", "Indischer Ozean", "Arktischer Ozean"]),
    C("What is the chemical symbol for oxygen?",
      ["O", "Ox", "Oy", "Om"],
      "Jaki jest symbol chemiczny tlenu?",
      ["O", "Ox", "Oy", "Om"],
      "Was ist das chemische Symbol für Sauerstoff?",
      ["O", "Ox", "Oy", "Om"]),
    C("In which sport is the term 'love' used for a score of zero?",
      ["Tennis", "Golf", "Boxing", "Hockey"],
      "W którym sporcie 'love' oznacza zero punktów?",
      ["Tenis", "Golf", "Boks", "Hokej"],
      "In welcher Sportart bedeutet 'love' null Punkte?",
      ["Tennis", "Golf", "Boxen", "Hockey"]),
    C("Which planet do we live on?",
      ["Earth", "Mars", "Venus", "Jupiter"],
      "Na której planecie żyjemy?",
      ["Ziemia", "Mars", "Wenus", "Jowisz"],
      "Auf welchem Planeten leben wir?",
      ["Erde", "Mars", "Venus", "Jupiter"]),
    C("Who wrote the fairy tale 'The Little Mermaid'?",
      ["Hans Christian Andersen", "Brothers Grimm", "Aesop", "Charles Perrault"],
      "Kto napisał baśń 'Mała Syrenka'?",
      ["Hans Christian Andersen", "Bracia Grimm", "Ezop", "Charles Perrault"],
      "Wer schrieb das Märchen 'Die kleine Meerjungfrau'?",
      ["Hans Christian Andersen", "Brüder Grimm", "Äsop", "Charles Perrault"]),
    C("What is the currency of the United States?",
      ["Dollar", "Euro", "Pound", "Yen"],
      "Jaka jest waluta Stanów Zjednoczonych?",
      ["Dolar", "Euro", "Funt", "Jen"],
      "Was ist die Währung der Vereinigten Staaten?",
      ["Dollar", "Euro", "Pfund", "Yen"]),
    C("How many minutes are there in two hours?",
      ["120", "60", "90", "100"],
      "Ile minut mają dwie godziny?",
      ["120", "60", "90", "100"],
      "Wie viele Minuten haben zwei Stunden?",
      ["120", "60", "90", "100"]),
    C("Which river flows through Warsaw?",
      ["Vistula", "Oder", "Warta", "Elbe"],
      "Która rzeka przepływa przez Warszawę?",
      ["Wisła", "Odra", "Warta", "Łaba"],
      "Welcher Fluss fließt durch Warschau?",
      ["Weichsel", "Oder", "Warthe", "Elbe"]),
    C("What do bees produce that is used as a sweetener?",
      ["Honey", "Maple syrup", "Sugar beet", "Molasses"],
      "Co pszczoły wytwarzają jako słodzik?",
      ["Miód", "Syrop klonowy", "Burak cukrowy", "Melasa"],
      "Was erzeugen Bienen, das man als Süßungsmittel nutzt?",
      ["Honig", "Ahornsirup", "Zuckerrübe", "Melasse"]),
    C("Which German city is home to the Brandenburg Gate?",
      ["Berlin", "Munich", "Hamburg", "Cologne"],
      "W którym niemieckim mieście stoi Brama Brandenburska?",
      ["Berlin", "Monachium", "Hamburg", "Kolonia"],
      "In welcher deutschen Stadt steht das Brandenburger Tor?",
      ["Berlin", "München", "Hamburg", "Köln"]),
    C("How many sides does a pentagon have?",
      ["5", "6", "7", "8"],
      "Ile boków ma pięciokąt?",
      ["5", "6", "7", "8"],
      "Wie viele Seiten hat ein Fünfeck?",
      ["5", "6", "7", "8"]),
    C("Which season comes after spring in the northern hemisphere?",
      ["Summer", "Winter", "Autumn", "Monsoon"],
      "Która pora roku następuje po wiośnie na półkuli północnej?",
      ["Lato", "Zima", "Jesień", "Monsun"],
      "Welche Jahreszeit folgt auf den Frühling auf der Nordhalbkugel?",
      ["Sommer", "Winter", "Herbst", "Monsun"]),
    C("What is the largest continent by area?",
      ["Asia", "Africa", "Europe", "Antarctica"],
      "Który kontynent jest największy powierzchniowo?",
      ["Azja", "Afryka", "Europa", "Antarktyda"],
      "Welcher Kontinent ist flächenmäßig der größte?",
      ["Asien", "Afrika", "Europa", "Antarktika"]),
    C("Which instrument has black and white keys?",
      ["Piano", "Violin", "Flute", "Harp"],
      "Który instrument ma czarne i białe klawisze?",
      ["Fortepian", "Skrzypce", "Flet", "Harfa"],
      "Welches Instrument hat schwarze und weiße Tasten?",
      ["Klavier", "Geige", "Flöte", "Harfe"]),
    C("How many players from one team are on the court in volleyball?",
      ["6", "5", "7", "11"],
      "Ilu zawodników jednej drużyny jest na boisku w siatkówce?",
      ["6", "5", "7", "11"],
      "Wie viele Spieler einer Mannschaft stehen beim Volleyball auf dem Feld?",
      ["6", "5", "7", "11"]),
    C("Which of these is a primary colour in painting?",
      ["Blue", "Green", "Pink", "Brown"],
      "Który z tych kolorów jest podstawowy w malarstwie?",
      ["Niebieski", "Zielony", "Różowy", "Brązowy"],
      "Welche dieser Farben ist eine Grundfarbe in der Malerei?",
      ["Blau", "Grün", "Rosa", "Braun"]),
    C("In chess, which piece is the most valuable besides the king?",
      ["Queen", "Knight", "Bishop", "Pawn"],
      "W szachach która figura jest najcenniejsza poza królem?",
      ["Hetman", "Skoczek", "Goniec", "Pion"],
      "Welche Schachfigur ist außer dem König die wertvollste?",
      ["Dame", "Springer", "Läufer", "Bauer"]),
    C("Which country is famous for the tulip and for windmills?",
      ["the Netherlands", "Denmark", "Belgium", "Switzerland"],
      "Który kraj słynie z tulipanów i wiatraków?",
      ["Holandia", "Dania", "Belgia", "Szwajcaria"],
      "Welches Land ist für Tulpen und Windmühlen bekannt?",
      ["die Niederlande", "Dänemark", "Belgien", "die Schweiz"]),
    C("What gas do humans need to breathe?",
      ["Oxygen", "Nitrogen only", "Helium", "Argon"],
      "Jakiego gazu człowiek potrzebuje do oddychania?",
      ["Tlenu", "Tylko azotu", "Helu", "Argonu"],
      "Welches Gas braucht der Mensch zum Atmen?",
      ["Sauerstoff", "Nur Stickstoff", "Helium", "Argon"]),
    C("Which city hosted the ancient Olympic Games?",
      ["Olympia", "Athens only in modern times", "Sparta", "Rome"],
      "W którym miejscu odbywały się starożytne igrzyska olimpijskie?",
      ["Olimpia", "Tylko nowożytne Ateny", "Sparta", "Rzym"],
      "Wo fanden die antiken Olympischen Spiele statt?",
      ["Olympia", "Nur das moderne Athen", "Sparta", "Rom"]),
    C("What is the main language of Brazil?",
      ["Portuguese", "Spanish", "French", "Italian"],
      "Jaki jest główny język Brazylii?",
      ["Portugalski", "Hiszpański", "Francuski", "Włoski"],
      "Was ist die Hauptsprache Brasiliens?",
      ["Portugiesisch", "Spanisch", "Französisch", "Italienisch"]),
    C("Which Polish city is known as the former royal capital?",
      ["Kraków", "Gdańsk", "Poznań", "Lublin"],
      "Które polskie miasto było dawną stolicą królewską?",
      ["Kraków", "Gdańsk", "Poznań", "Lublin"],
      "Welche polnische Stadt war die frühere Königsresidenz?",
      ["Krakau", "Danzig", "Posen", "Lublin"]),
    C("How many degrees are in a full circle?",
      ["360", "180", "100", "90"],
      "Ile stopni ma pełny kąt?",
      ["360", "180", "100", "90"],
      "Wie viele Grad hat ein voller Kreis?",
      ["360", "180", "100", "90"]),
    C("Which composer wrote 'Für Elise'?",
      ["Beethoven", "Mozart", "Bach", "Chopin"],
      "Który kompozytor napisał 'Für Elise'?",
      ["Beethoven", "Mozart", "Bach", "Chopin"],
      "Wer komponierte 'Für Elise'?",
      ["Beethoven", "Mozart", "Bach", "Chopin"]),
    C("What is the capital of Austria?",
      ["Vienna", "Salzburg", "Innsbruck", "Graz"],
      "Jaka jest stolica Austrii?",
      ["Wiedeń", "Salzburg", "Innsbruck", "Graz"],
      "Was ist die Hauptstadt Österreichs?",
      ["Wien", "Salzburg", "Innsbruck", "Graz"]),
    C("Which of these animals is a mammal?",
      ["Dolphin", "Shark", "Tuna", "Crocodile"],
      "Które z tych zwierząt jest ssakiem?",
      ["Delfin", "Rekin", "Tuńczyk", "Krokodyl"],
      "Welches dieser Tiere ist ein Säugetier?",
      ["Delfin", "Hai", "Thunfisch", "Krokodil"]),
]
