from qfmt import C

L4 = [
    C("Which city is the capital of Italy?",
      ["Rome", "Milan", "Naples", "Turin"],
      "Które miasto jest stolicą Włoch?",
      ["Rzym", "Mediolan", "Neapol", "Turyn"],
      "Welche Stadt ist die Hauptstadt Italiens?",
      ["Rom", "Mailand", "Neapel", "Turin"]),
    C("Which planet is the largest in the Solar System?",
      ["Jupiter", "Saturn", "Neptune", "Uranus"],
      "Która planeta jest największa w Układzie Słonecznym?",
      ["Jowisz", "Saturn", "Neptun", "Uran"],
      "Welcher Planet ist der größte im Sonnensystem?",
      ["Jupiter", "Saturn", "Neptun", "Uranus"]),
    C("In which country do kangaroos live in the wild?",
      ["Australia", "India", "South Africa", "Brazil"],
      "W którym kraju kangury żyją na wolności?",
      ["Australia", "Indie", "Południowa Afryka", "Brazylia"],
      "In welchem Land leben Kängurus in freier Wildbahn?",
      ["Australien", "Indien", "Südafrika", "Brasilien"]),
    C("What is the currency of the United Kingdom?",
      ["Pound sterling", "Euro", "Dollar", "Franc"],
      "Jaka jest waluta Zjednoczonego Królestwa?",
      ["Funt szterling", "Euro", "Dolar", "Frank"],
      "Was ist die Währung des Vereinigten Königreichs?",
      ["Pfund Sterling", "Euro", "Dollar", "Franken"]),
    C("How many rings appear on the Olympic symbol?",
      ["5", "4", "6", "3"],
      "Ile kółek ma olimpijski symbol?",
      ["5", "4", "6", "3"],
      "Wie viele Ringe hat das olympische Symbol?",
      ["5", "4", "6", "3"]),
    C("What is the capital of Spain?",
      ["Madrid", "Barcelona", "Seville", "Valencia"],
      "Jaka jest stolica Hiszpanii?",
      ["Madryt", "Barcelona", "Sewilla", "Walencja"],
      "Was ist die Hauptstadt Spaniens?",
      ["Madrid", "Barcelona", "Sevilla", "Valencia"]),
    C("Who painted The Starry Night?",
      ["Vincent van Gogh", "Claude Monet", "Rembrandt", "Paul Cézanne"],
      "Kto namalował 'Gwiaździstą noc'?",
      ["Vincent van Gogh", "Claude Monet", "Rembrandt", "Paul Cézanne"],
      "Wer malte 'Die Sternennacht'?",
      ["Vincent van Gogh", "Claude Monet", "Rembrandt", "Paul Cézanne"]),
    C("Which fruit is traditionally used to make wine?",
      ["Grapes", "Apples", "Plums", "Cherries"],
      "Z jakiego owocu tradycyjnie robi się wino?",
      ["Winogron", "Jabłek", "Śliwek", "Wiśni"],
      "Aus welcher Frucht wird traditionell Wein gemacht?",
      ["Trauben", "Äpfel", "Pflaumen", "Kirschen"]),
    C("In which country is Machu Picchu?",
      ["Peru", "Mexico", "Chile", "Bolivia"],
      "W którym kraju leży Machu Picchu?",
      ["Peru", "Meksyk", "Chile", "Boliwia"],
      "In welchem Land liegt Machu Picchu?",
      ["Peru", "Mexiko", "Chile", "Bolivien"]),
    C("How many teeth does an adult human usually have?",
      ["32", "28", "24", "36"],
      "Ile zębów ma zwykle dorosły człowiek?",
      ["32", "28", "24", "36"],
      "Wie viele Zähne hat ein Erwachsener gewöhnlich?",
      ["32", "28", "24", "36"]),
    C("What is the capital of Germany?",
      ["Berlin", "Bonn", "Hamburg", "Munich"],
      "Jaka jest stolica Niemiec?",
      ["Berlin", "Bonn", "Hamburg", "Monachium"],
      "Was ist die Hauptstadt Deutschlands?",
      ["Berlin", "Bonn", "Hamburg", "München"]),
    C("In which country did pizza originate?",
      ["Italy", "France", "Greece", "Spain"],
      "W którym kraju powstała pizza?",
      ["Włochy", "Francja", "Grecja", "Hiszpania"],
      "In welchem Land entstand die Pizza?",
      ["Italien", "Frankreich", "Griechenland", "Spanien"]),
    C("Which river is traditionally named the longest in the world?",
      ["Nile", "Amazon", "Yangtze", "Mississippi"],
      "Która rzeka jest tradycyjnie uważana za najdłuższą na świecie?",
      ["Nil", "Amazonka", "Jangcy", "Missisipi"],
      "Welcher Fluss gilt traditionell als der längste der Welt?",
      ["Nil", "Amazonas", "Jangtse", "Mississippi"]),
    C("Who is the Roman god of war?",
      ["Mars", "Jupiter", "Neptune", "Apollo"],
      "Kto w mitologii rzymskiej jest bogiem wojny?",
      ["Mars", "Jowisz", "Neptun", "Apollo"],
      "Wer ist in der römischen Mythologie der Kriegsgott?",
      ["Mars", "Jupiter", "Neptun", "Apollo"]),
    C("How many days are there in a leap year?",
      ["366", "365", "364", "360"],
      "Ile dni ma rok przestępny?",
      ["366", "365", "364", "360"],
      "Wie viele Tage hat ein Schaltjahr?",
      ["366", "365", "364", "360"]),
    C("In which country is the city of Prague?",
      ["Czech Republic", "Austria", "Slovakia", "Hungary"],
      "W którym kraju leży Praga?",
      ["Czechy", "Austria", "Słowacja", "Węgry"],
      "In welchem Land liegt Prag?",
      ["Tschechien", "Österreich", "Slowakei", "Ungarn"]),
    C("Who wrote the Harry Potter novels?",
      ["J.K. Rowling", "C.S. Lewis", "J.R.R. Tolkien", "Roald Dahl"],
      "Kto napisał powieści o Harrym Potterze?",
      ["J.K. Rowling", "C.S. Lewis", "J.R.R. Tolkien", "Roald Dahl"],
      "Wer schrieb die Harry-Potter-Romane?",
      ["J.K. Rowling", "C.S. Lewis", "J.R.R. Tolkien", "Roald Dahl"]),
    C("What metal covers the Statue of Liberty?",
      ["Copper", "Iron", "Gold", "Bronze"],
      "Jakim metalem pokryta jest Statua Wolności?",
      ["Miedzią", "Żelazem", "Złotem", "Brązem"],
      "Mit welchem Metall ist die Freiheitsstatue überzogen?",
      ["Kupfer", "Eisen", "Gold", "Bronze"]),
    C("How many continents are usually taught in school?",
      ["7", "5", "6", "8"],
      "Ile kontynentów zwykle wymienia się w szkole?",
      ["7", "5", "6", "8"],
      "Wie viele Kontinente werden meist in der Schule genannt?",
      ["7", "5", "6", "8"]),
    C("Who was the first President of the United States?",
      ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"],
      "Kto był pierwszym prezydentem Stanów Zjednoczonych?",
      ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"],
      "Wer war der erste Präsident der Vereinigten Staaten?",
      ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"]),
    C("In The Wizard of Oz, Dorothy wants to return to which US state?",
      ["Kansas", "Texas", "Ohio", "Florida"],
      "W 'Czarnoksiężniku z Oz' Dorothy chce wrócić do którego stanu USA?",
      ["Kansas", "Teksas", "Ohio", "Floryda"],
      "In 'Der Zauberer von Oz' will Dorothy in welchen US-Bundesstaat zurück?",
      ["Kansas", "Texas", "Ohio", "Florida"]),
    C("What is the capital of Ireland?",
      ["Dublin", "Cork", "Belfast", "Galway"],
      "Jaka jest stolica Irlandii?",
      ["Dublin", "Cork", "Belfast", "Galway"],
      "Was ist die Hauptstadt Irlands?",
      ["Dublin", "Cork", "Belfast", "Galway"]),
    C("Who wrote The Odyssey?",
      ["Homer", "Virgil", "Sophocles", "Ovid"],
      "Kto jest autorem 'Odysei'?",
      ["Homer", "Wergiliusz", "Sofokles", "Owidiusz"],
      "Wer verfasste die 'Odyssee'?",
      ["Homer", "Vergil", "Sophokles", "Ovid"]),
    C("In which Italian city does the Leaning Tower stand?",
      ["Pisa", "Florence", "Bologna", "Siena"],
      "W którym włoskim mieście stoi Krzywa Wieża?",
      ["Piza", "Florencja", "Bolonia", "Siena"],
      "In welcher italienischen Stadt steht der Schiefe Turm?",
      ["Pisa", "Florenz", "Bologna", "Siena"]),
    C("In which country was the Great Wall built?",
      ["China", "Japan", "Mongolia", "Korea"],
      "W którym kraju zbudowano Wielki Mur?",
      ["Chiny", "Japonia", "Mongolia", "Korea"],
      "In welchem Land wurde die Große Mauer gebaut?",
      ["China", "Japan", "Mongolei", "Korea"]),
    C("What currency is used in Germany?",
      ["Euro", "Mark", "Franc", "Krone"],
      "Jaka waluta obowiązuje w Niemczech?",
      ["Euro", "Marka", "Frank", "Korona"],
      "Welche Währung gilt in Deutschland?",
      ["Euro", "Mark", "Franken", "Krone"]),
    C("Which gas do humans need to breathe?",
      ["Oxygen", "Nitrogen", "Helium", "Carbon dioxide"],
      "Jakiego gazu ludzie potrzebują do oddychania?",
      ["Tlenu", "Azotu", "Helu", "Dwutlenku węgla"],
      "Welches Gas brauchen Menschen zum Atmen?",
      ["Sauerstoff", "Stickstoff", "Helium", "Kohlenstoffdioxid"]),
]

L5 = [
    C("What is the chemical symbol for silver?",
      ["Ag", "Si", "Sv", "Sr"],
      "Jaki jest symbol chemiczny srebra?",
      ["Ag", "Si", "Sv", "Sr"],
      "Was ist das chemische Symbol für Silber?",
      ["Ag", "Si", "Sv", "Sr"]),
    C("What is the capital of Sweden?",
      ["Stockholm", "Oslo", "Copenhagen", "Helsinki"],
      "Jaka jest stolica Szwecji?",
      ["Sztokholm", "Oslo", "Kopenhaga", "Helsinki"],
      "Was ist die Hauptstadt Schwedens?",
      ["Stockholm", "Oslo", "Kopenhagen", "Helsinki"]),
    C("Which organ produces insulin?",
      ["Pancreas", "Liver", "Spleen", "Stomach"],
      "Który narząd wytwarza insulinę?",
      ["Trzustka", "Wątroba", "Śledziona", "Żołądek"],
      "Welches Organ bildet Insulin?",
      ["Bauchspeicheldrüse", "Leber", "Milz", "Magen"]),
    C("In which year did the Second World War end in Europe?",
      ["1945", "1939", "1918", "1948"],
      "W którym roku zakończyła się w Europie II wojna światowa?",
      ["1945", "1939", "1918", "1948"],
      "In welchem Jahr endete der Zweite Weltkrieg in Europa?",
      ["1945", "1939", "1918", "1948"]),
    C("Who composed the opera The Magic Flute?",
      ["Wolfgang Amadeus Mozart", "Giuseppe Verdi", "Richard Wagner", "Franz Schubert"],
      "Kto skomponował operę 'Czarodziejski flet'?",
      ["Wolfgang Amadeus Mozart", "Giuseppe Verdi", "Richard Wagner", "Franz Schubert"],
      "Wer komponierte die Oper 'Die Zauberflöte'?",
      ["Wolfgang Amadeus Mozart", "Giuseppe Verdi", "Richard Wagner", "Franz Schubert"]),
    C("What is the longest river in Europe?",
      ["Volga", "Danube", "Rhine", "Dnieper"],
      "Która rzeka jest najdłuższa w Europie?",
      ["Wołga", "Dunaj", "Ren", "Dniepr"],
      "Welcher Fluss ist der längste in Europa?",
      ["Wolga", "Donau", "Rhein", "Dnepr"]),
    C("Who sculpted the marble statue of David in Florence?",
      ["Michelangelo", "Donatello", "Bernini", "Rodin"],
      "Kto wyrzeźbił marmurowego Dawida we Florencji?",
      ["Michał Anioł", "Donatello", "Bernini", "Rodin"],
      "Wer schuf die Marmorstatue des David in Florenz?",
      ["Michelangelo", "Donatello", "Bernini", "Rodin"]),
    C("What is the capital of Portugal?",
      ["Lisbon", "Porto", "Madrid", "Coimbra"],
      "Jaka jest stolica Portugalii?",
      ["Lizbona", "Porto", "Madryt", "Coimbra"],
      "Was ist die Hauptstadt Portugals?",
      ["Lissabon", "Porto", "Madrid", "Coimbra"]),
    C("Which chemical element has the atomic number 1?",
      ["Hydrogen", "Helium", "Lithium", "Oxygen"],
      "Który pierwiastek chemiczny ma liczbę atomową 1?",
      ["Wodór", "Hel", "Lit", "Tlen"],
      "Welches chemische Element hat die Ordnungszahl 1?",
      ["Wasserstoff", "Helium", "Lithium", "Sauerstoff"]),
    C("Who is credited with inventing the telephone?",
      ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"],
      "Komu przypisuje się wynalezienie telefonu?",
      ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"],
      "Wem wird die Erfindung des Telefons zugeschrieben?",
      ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"]),
    C("In which Polish city does Wawel Castle stand?",
      ["Kraków", "Poznań", "Lublin", "Gdańsk"],
      "W którym polskim mieście stoi Zamek Królewski na Wawelu?",
      ["Kraków", "Poznań", "Lublin", "Gdańsk"],
      "In welcher polnischen Stadt steht das Wawelschloss?",
      ["Krakau", "Posen", "Lublin", "Danzig"]),
    C("What is the official language of Brazil?",
      ["Portuguese", "Spanish", "French", "Italian"],
      "Jaki jest język urzędowy Brazylii?",
      ["Portugalski", "Hiszpański", "Francuski", "Włoski"],
      "Was ist die Amtssprache Brasiliens?",
      ["Portugiesisch", "Spanisch", "Französisch", "Italienisch"]),
    C("How many strings does a standard guitar have?",
      ["6", "4", "5", "8"],
      "Ile strun ma standardowa gitara?",
      ["6", "4", "5", "8"],
      "Wie viele Saiten hat eine gewöhnliche Gitarre?",
      ["6", "4", "5", "8"]),
    C("Which planet orbits closest to the Sun?",
      ["Mercury", "Venus", "Earth", "Mars"],
      "Która planeta krąży najbliżej Słońca?",
      ["Merkury", "Wenus", "Ziemia", "Mars"],
      "Welcher Planet kreist der Sonne am nächsten?",
      ["Merkur", "Venus", "Erde", "Mars"]),
    C("Who wrote Pride and Prejudice?",
      ["Jane Austen", "Charlotte Brontë", "George Eliot", "Emily Brontë"],
      "Kto napisał 'Dumę i uprzedzenie'?",
      ["Jane Austen", "Charlotte Brontë", "George Eliot", "Emily Brontë"],
      "Wer schrieb 'Stolz und Vorurteil'?",
      ["Jane Austen", "Charlotte Brontë", "George Eliot", "Emily Brontë"]),
    C("What is the hardest naturally occurring mineral?",
      ["Diamond", "Quartz", "Topaz", "Corundum"],
      "Jaki jest najtwardszy minerał występujący w przyrodzie?",
      ["Diament", "Kwarc", "Topaz", "Korund"],
      "Was ist das härteste natürlich vorkommende Mineral?",
      ["Diamant", "Quarz", "Topas", "Korund"]),
    C("What is the capital of Austria?",
      ["Vienna", "Salzburg", "Innsbruck", "Graz"],
      "Jaka jest stolica Austrii?",
      ["Wiedeń", "Salzburg", "Innsbruck", "Graz"],
      "Was ist die Hauptstadt Österreichs?",
      ["Wien", "Salzburg", "Innsbruck", "Graz"]),
    C("Which sea lies between Great Britain and Scandinavia?",
      ["North Sea", "Baltic Sea", "Irish Sea", "Celtic Sea"],
      "Które morze leży między Wielką Brytanią a Skandynawią?",
      ["Morze Północne", "Bałtyk", "Morze Irlandzkie", "Morze Celtyckie"],
      "Welches Meer liegt zwischen Großbritannien und Skandinavien?",
      ["Nordsee", "Ostsee", "Irische See", "Keltische See"]),
    C("What is the SI unit of force?",
      ["Newton", "Joule", "Watt", "Pascal"],
      "Jaka jest jednostka siły w układzie SI?",
      ["Niuton", "Dżul", "Wat", "Paskal"],
      "Was ist die SI-Einheit der Kraft?",
      ["Newton", "Joule", "Watt", "Pascal"]),
    C("In which country is the Taj Mahal?",
      ["India", "Pakistan", "Iran", "Turkey"],
      "W którym kraju stoi Tadż Mahal?",
      ["Indie", "Pakistan", "Iran", "Turcja"],
      "In welchem Land steht das Taj Mahal?",
      ["Indien", "Pakistan", "Iran", "Türkei"]),
    C("Who directed the film Psycho?",
      ["Alfred Hitchcock", "John Huston", "Stanley Kubrick", "Billy Wilder"],
      "Kto wyreżyserował film 'Psychoza'?",
      ["Alfred Hitchcock", "John Huston", "Stanley Kubrick", "Billy Wilder"],
      "Wer führte bei dem Film 'Psycho' Regie?",
      ["Alfred Hitchcock", "John Huston", "Stanley Kubrick", "Billy Wilder"]),
    C("Which light gas is often used to fill floating party balloons?",
      ["Helium", "Oxygen", "Nitrogen", "Argon"],
      "Jakim lekkim gazem często napełnia się unoszące się balony?",
      ["Helem", "Tlenem", "Azotem", "Argonem"],
      "Welches leichte Gas füllt oft schwebende Luftballons?",
      ["Helium", "Sauerstoff", "Stickstoff", "Argon"]),
    C("What is the capital of Greece?",
      ["Athens", "Thessaloniki", "Sparta", "Rhodes"],
      "Jaka jest stolica Grecji?",
      ["Ateny", "Saloniki", "Sparta", "Rodos"],
      "Was ist die Hauptstadt Griechenlands?",
      ["Athen", "Thessaloniki", "Sparta", "Rhodos"]),
    C("Who composed The Four Seasons?",
      ["Antonio Vivaldi", "Johann Sebastian Bach", "Georg Friedrich Händel", "Franz Liszt"],
      "Kto skomponował 'Cztery pory roku'?",
      ["Antonio Vivaldi", "Johann Sebastian Bach", "Georg Friedrich Händel", "Franz Liszt"],
      "Wer komponierte 'Die vier Jahreszeiten'?",
      ["Antonio Vivaldi", "Johann Sebastian Bach", "Georg Friedrich Händel", "Franz Liszt"]),
    C("What process do green plants use to make food from sunlight?",
      ["Photosynthesis", "Fermentation", "Respiration", "Transpiration"],
      "Jakim procesem zielone rośliny wytwarzają pokarm ze światła słonecznego?",
      ["Fotosyntezą", "Fermentacją", "Oddychaniem", "Transpiracją"],
      "Mit welchem Prozess erzeugen grüne Pflanzen aus Sonnenlicht Nahrung?",
      ["Photosynthese", "Gärung", "Atmung", "Transpiration"]),
    C("What is the capital of Scotland?",
      ["Edinburgh", "Glasgow", "Aberdeen", "Inverness"],
      "Jaka jest stolica Szkocji?",
      ["Edynburg", "Glasgow", "Aberdeen", "Inverness"],
      "Was ist die Hauptstadt Schottlands?",
      ["Edinburgh", "Glasgow", "Aberdeen", "Inverness"]),
    C("Who wrote On the Origin of Species?",
      ["Charles Darwin", "Gregor Mendel", "Alfred Wallace", "Thomas Huxley"],
      "Kto napisał 'O powstawaniu gatunków'?",
      ["Charles Darwin", "Gregor Mendel", "Alfred Wallace", "Thomas Huxley"],
      "Wer schrieb 'Über die Entstehung der Arten'?",
      ["Charles Darwin", "Gregor Mendel", "Alfred Wallace", "Thomas Huxley"]),
]

L6 = [
    C("Which scientist born in Warsaw won Nobel Prizes in two different sciences?",
      ["Marie Curie", "Albert Einstein", "Niels Bohr", "Max Planck"],
      "Która uczona urodzona w Warszawie zdobyła Nobla w dwóch dziedzinach?",
      ["Maria Skłodowska-Curie", "Albert Einstein", "Niels Bohr", "Max Planck"],
      "Welche in Warschau geborene Wissenschaftlerin gewann Nobelpreise in zwei Fächern?",
      ["Marie Curie", "Albert Einstein", "Niels Bohr", "Max Planck"]),
    C("What is the capital of Hungary?",
      ["Budapest", "Bucharest", "Belgrade", "Bratislava"],
      "Jaka jest stolica Węgier?",
      ["Budapeszt", "Bukareszt", "Belgrad", "Bratysława"],
      "Was ist die Hauptstadt Ungarns?",
      ["Budapest", "Bukarest", "Belgrad", "Bratislava"]),
    C("Who wrote the tragic play Faust?",
      ["Johann Wolfgang von Goethe", "Friedrich Schiller", "Heinrich Heine", "Gotthold Lessing"],
      "Kto napisał tragedię 'Faust'?",
      ["Johann Wolfgang von Goethe", "Friedrich Schiller", "Heinrich Heine", "Gotthold Lessing"],
      "Wer schrieb das Trauerspiel 'Faust'?",
      ["Johann Wolfgang von Goethe", "Friedrich Schiller", "Heinrich Heine", "Gotthold Lessing"]),
    C("What is the chemical formula of common table salt?",
      ["NaCl", "KCl", "NaOH", "CaCO3"],
      "Jaki jest wzór chemiczny zwykłej soli kuchennej?",
      ["NaCl", "KCl", "NaOH", "CaCO3"],
      "Was ist die chemische Formel von gewöhnlichem Speisesalz?",
      ["NaCl", "KCl", "NaOH", "CaCO3"]),
    C("Which strait divides Istanbul between Europe and Asia?",
      ["Bosporus", "Dardanelles", "Gibraltar", "Hormuz"],
      "Która cieśnina dzieli Stambuł na część europejską i azjatycką?",
      ["Bosfor", "Dardanele", "Gibraltar", "Ormuz"],
      "Welche Meerenge teilt Istanbul in Europa und Asien?",
      ["Bosporus", "Dardanellen", "Gibraltar", "Hormus"]),
    C("Who painted Guernica?",
      ["Pablo Picasso", "Joan Miró", "Henri Matisse", "Georges Braque"],
      "Kto namalował 'Guernicę'?",
      ["Pablo Picasso", "Joan Miró", "Henri Matisse", "Georges Braque"],
      "Wer malte 'Guernica'?",
      ["Pablo Picasso", "Joan Miró", "Henri Matisse", "Georges Braque"]),
    C("In which year did the Berlin Wall fall?",
      ["1989", "1961", "1991", "1979"],
      "W którym roku upadł Mur Berliński?",
      ["1989", "1961", "1991", "1979"],
      "In welchem Jahr fiel die Berliner Mauer?",
      ["1989", "1961", "1991", "1979"]),
    C("What is the largest moon of Saturn?",
      ["Titan", "Europa", "Callisto", "Triton"],
      "Który księżyc Saturna jest największy?",
      ["Tytan", "Europa", "Kallisto", "Tryton"],
      "Welcher Mond des Saturn ist der größte?",
      ["Titan", "Europa", "Kallisto", "Triton"]),
    C("Who wrote Crime and Punishment?",
      ["Fyodor Dostoevsky", "Leo Tolstoy", "Anton Chekhov", "Ivan Turgenev"],
      "Kto napisał 'Zbrodnię i karę'?",
      ["Fiodor Dostojewski", "Lew Tołstoj", "Anton Czechow", "Iwan Turgieniew"],
      "Wer schrieb 'Schuld und Sühne'?",
      ["Fjodor Dostojewski", "Leo Tolstoi", "Anton Tschechow", "Iwan Turgenew"]),
    C("Which river flows through Cologne?",
      ["Rhine", "Elbe", "Moselle", "Main"],
      "Która rzeka przepływa przez Kolonię?",
      ["Ren", "Łaba", "Mozela", "Men"],
      "Welcher Fluss fließt durch Köln?",
      ["Rhein", "Elbe", "Mosel", "Main"]),
    C("What does the abbreviation DNA stand for?",
      ["Deoxyribonucleic acid", "Dynamic nuclear array", "Dual nucleotide agent", "Direct nitrogen acid"],
      "Co oznacza skrót DNA?",
      ["Kwas deoksyrybonukleinowy", "Dynamiczny nukleotyd aktywny", "Podwójny nośnik azotu", "Bezpośredni kwas azotowy"],
      "Wofür steht die Abkürzung DNA?",
      ["Desoxyribonukleinsäure", "Dynamisches Nukleararray", "Doppeltes Nukleotidagens", "Direkte Stickstoffsäure"]),
    C("What is the capital of Finland?",
      ["Helsinki", "Tallinn", "Stockholm", "Turku"],
      "Jaka jest stolica Finlandii?",
      ["Helsinki", "Tallinn", "Sztokholm", "Turku"],
      "Was ist die Hauptstadt Finnlands?",
      ["Helsinki", "Tallinn", "Stockholm", "Turku"]),
    C("Who discovered X-rays?",
      ["Wilhelm Röntgen", "Marie Curie", "Henri Becquerel", "Max von Laue"],
      "Kto odkrył promienie X?",
      ["Wilhelm Röntgen", "Maria Skłodowska-Curie", "Henri Becquerel", "Max von Laue"],
      "Wer entdeckte die X-Strahlen?",
      ["Wilhelm Röntgen", "Marie Curie", "Henri Becquerel", "Max von Laue"]),
    C("What is the highest mountain in Africa?",
      ["Kilimanjaro", "Mount Kenya", "Atlas", "Drakensberg"],
      "Jaka jest najwyższa góra Afryki?",
      ["Kilimandżaro", "Mount Kenya", "Atlas", "Drakensberge"],
      "Was ist der höchste Berg Afrikas?",
      ["Kilimandscharo", "Mount Kenya", "Atlas", "Drakensberge"]),
    C("What is the currency of Switzerland?",
      ["Swiss franc", "Euro", "Krone", "Schilling"],
      "Jaka jest waluta Szwajcarii?",
      ["Frank szwajcarski", "Euro", "Korona", "Szyling"],
      "Was ist die Währung der Schweiz?",
      ["Schweizer Franken", "Euro", "Krone", "Schilling"]),
    C("Who composed the ballet The Nutcracker?",
      ["Pyotr Tchaikovsky", "Igor Stravinsky", "Sergei Prokofiev", "Modest Mussorgsky"],
      "Kto skomponował balet 'Dziadek do orzechów'?",
      ["Piotr Czajkowski", "Igor Strawinski", "Siergiej Prokofiew", "Modest Musorgski"],
      "Wer komponierte das Ballett 'Der Nussknacker'?",
      ["Pjotr Tschaikowski", "Igor Strawinsky", "Sergei Prokofjew", "Modest Mussorgski"]),
    C("In Greek myth, which youth flew too close to the Sun?",
      ["Icarus", "Theseus", "Perseus", "Orpheus"],
      "Który młodzieniec w micie greckim podleciał zbyt blisko Słońca?",
      ["Ikar", "Tezeusz", "Perseusz", "Orfeusz"],
      "Welcher Jüngling flog im griechischen Mythos der Sonne zu nahe?",
      ["Ikarus", "Theseus", "Perseus", "Orpheus"]),
    C("Which cell organelle is often called the powerhouse of the cell?",
      ["Mitochondrion", "Nucleus", "Ribosome", "Golgi apparatus"],
      "Która organella bywa nazywana elektrownią komórki?",
      ["Mitochondrium", "Jądro komórkowe", "Rybosom", "Aparat Golgiego"],
      "Welches Zellorganell heißt oft das Kraftwerk der Zelle?",
      ["Mitochondrium", "Zellkern", "Ribosom", "Golgi-Apparat"]),
    C("What is the capital of Norway?",
      ["Oslo", "Bergen", "Stavanger", "Trondheim"],
      "Jaka jest stolica Norwegii?",
      ["Oslo", "Bergen", "Stavanger", "Trondheim"],
      "Was ist die Hauptstadt Norwegens?",
      ["Oslo", "Bergen", "Stavanger", "Trondheim"]),
    C("Who wrote The Divine Comedy?",
      ["Dante Alighieri", "Petrarch", "Boccaccio", "Ariosto"],
      "Kto napisał 'Boską Komedię'?",
      ["Dante Alighieri", "Petrarka", "Boccaccio", "Ariosto"],
      "Wer schrieb die 'Göttliche Komödie'?",
      ["Dante Alighieri", "Petrarca", "Boccaccio", "Ariosto"]),
    C("What pH value is considered chemically neutral?",
      ["7", "0", "14", "1"],
      "Jaka wartość pH uchodzi za chemicznie obojętną?",
      ["7", "0", "14", "1"],
      "Welcher pH-Wert gilt als chemisch neutral?",
      ["7", "0", "14", "1"]),
    C("Who was the first person to walk on the Moon?",
      ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"],
      "Kto jako pierwszy stanął na Księżycu?",
      ["Neil Armstrong", "Buzz Aldrin", "Jurij Gagarin", "John Glenn"],
      "Wer betrat als Erster den Mond?",
      ["Neil Armstrong", "Buzz Aldrin", "Juri Gagarin", "John Glenn"]),
    C("What is the capital of Belgium?",
      ["Brussels", "Antwerp", "Bruges", "Ghent"],
      "Jaka jest stolica Belgii?",
      ["Bruksela", "Antwerpia", "Brugia", "Gandawa"],
      "Was ist die Hauptstadt Belgiens?",
      ["Brüssel", "Antwerpen", "Brügge", "Gent"]),
    C("Who directed the film Citizen Kane?",
      ["Orson Welles", "John Ford", "Frank Capra", "Howard Hawks"],
      "Kto wyreżyserował film 'Obywatel Kane'?",
      ["Orson Welles", "John Ford", "Frank Capra", "Howard Hawks"],
      "Wer führte bei dem Film 'Citizen Kane' Regie?",
      ["Orson Welles", "John Ford", "Frank Capra", "Howard Hawks"]),
    C("How many chromosomes are in a typical human body cell?",
      ["46", "23", "48", "32"],
      "Ile chromosomów ma typowa komórka ciała człowieka?",
      ["46", "23", "48", "32"],
      "Wie viele Chromosomen hat eine typische menschliche Körperzelle?",
      ["46", "23", "48", "32"]),
    C("In which country was Frédéric Chopin born?",
      ["Poland", "France", "Austria", "Germany"],
      "W którym kraju urodził się Fryderyk Chopin?",
      ["W Polsce", "We Francji", "W Austrii", "W Niemczech"],
      "In welchem Land wurde Frédéric Chopin geboren?",
      ["Polen", "Frankreich", "Österreich", "Deutschland"]),
    C("Through which London district does the Prime Meridian pass?",
      ["Greenwich", "Westminster", "Camden", "Chelsea"],
      "Przez którą dzielnicę Londynu przebiega południk zerowy?",
      ["Greenwich", "Westminster", "Camden", "Chelsea"],
      "Durch welchen Londoner Stadtteil verläuft der Nullmeridian?",
      ["Greenwich", "Westminster", "Camden", "Chelsea"]),
    C("In which year did Solidarity (Solidarność) emerge in Poland?",
      ["1980", "1968", "1989", "1970"],
      "W którym roku powstała Solidarność?",
      ["1980", "1968", "1989", "1970"],
      "In welchem Jahr entstand die Solidarność in Polen?",
      ["1980", "1968", "1989", "1970"]),
    C("Which German state has Munich as its capital?",
      ["Bavaria", "Saxony", "Hesse", "Brandenburg"],
      "Którego niemieckiego kraju związkowego stolicą jest Monachium?",
      ["Bawarii", "Saksonii", "Hesji", "Brandenburgii"],
      "Welches deutsche Bundesland hat München als Hauptstadt?",
      ["Bayern", "Sachsen", "Hessen", "Brandenburg"]),
    C("What is the traditional Polish beetroot soup called?",
      ["barszcz", "żurek", "rosół", "krupnik"],
      "Jak nazywa się tradycyjna polska zupa z buraków?",
      ["barszcz", "żurek", "rosół", "krupnik"],
      "Wie heißt die traditionelle polnische Rote-Bete-Suppe?",
      ["Barszcz", "Żurek", "Rosół", "Krupnik"]),
]
