from qfmt import C

L7 = [
    C("Who wrote The Metamorphosis, about Gregor Samsa?",
      ["Franz Kafka", "Thomas Mann", "Hermann Hesse", "Stefan Zweig"],
      "Kto napisał 'Przemianę', opowieść o Gregorze Samsie?",
      ["Franz Kafka", "Thomas Mann", "Hermann Hesse", "Stefan Zweig"],
      "Wer schrieb 'Die Verwandlung' über Gregor Samsa?",
      ["Franz Kafka", "Thomas Mann", "Hermann Hesse", "Stefan Zweig"]),
    C("What is the capital of Romania?",
      ["Bucharest", "Budapest", "Sofia", "Belgrade"],
      "Jaka jest stolica Rumunii?",
      ["Bukareszt", "Budapeszt", "Sofia", "Belgrad"],
      "Was ist die Hauptstadt Rumäniens?",
      ["Bukarest", "Budapest", "Sofia", "Belgrad"]),
    C("In which year was the Battle of Grunwald fought?",
      ["1410", "1683", "1415", "1525"],
      "W którym roku stoczono bitwę pod Grunwaldem?",
      ["1410", "1683", "1415", "1525"],
      "In welchem Jahr fand die Schlacht bei Tannenberg (Grunwald) statt?",
      ["1410", "1683", "1415", "1525"]),
    C("What is the SI unit of energy?",
      ["Joule", "Newton", "Watt", "Volt"],
      "Jaka jest jednostka energii w układzie SI?",
      ["Dżul", "Niuton", "Wat", "Wolt"],
      "Was ist die SI-Einheit der Energie?",
      ["Joule", "Newton", "Watt", "Volt"]),
    C("Who painted The Night Watch?",
      ["Rembrandt", "Vermeer", "Rubens", "Van Dyck"],
      "Kto namalował 'Straż nocną'?",
      ["Rembrandt", "Vermeer", "Rubens", "Van Dyck"],
      "Wer malte 'Die Nachtwache'?",
      ["Rembrandt", "Vermeer", "Rubens", "Van Dyck"]),
    C("Which chemical element is named after Poland?",
      ["Polonium", "Palladium", "Phosphorus", "Platinum"],
      "Który pierwiastek chemiczny nazwano od Polski?",
      ["Polon", "Pallad", "Fosfor", "Platyna"],
      "Welches chemische Element ist nach Polen benannt?",
      ["Polonium", "Palladium", "Phosphor", "Platin"]),
    C("What is the capital of Ukraine?",
      ["Kyiv", "Lviv", "Odesa", "Kharkiv"],
      "Jaka jest stolica Ukrainy?",
      ["Kijów", "Lwów", "Odessa", "Charków"],
      "Was ist die Hauptstadt der Ukraine?",
      ["Kiew", "Lwiw", "Odessa", "Charkiw"]),
    C("Who composed the opera Carmen?",
      ["Georges Bizet", "Giacomo Puccini", "Giuseppe Verdi", "Charles Gounod"],
      "Kto skomponował operę 'Carmen'?",
      ["Georges Bizet", "Giacomo Puccini", "Giuseppe Verdi", "Charles Gounod"],
      "Wer komponierte die Oper 'Carmen'?",
      ["Georges Bizet", "Giacomo Puccini", "Giuseppe Verdi", "Charles Gounod"]),
    C("In which year did the First World War begin?",
      ["1914", "1918", "1939", "1905"],
      "W którym roku wybuchła I wojna światowa?",
      ["1914", "1918", "1939", "1905"],
      "In welchem Jahr begann der Erste Weltkrieg?",
      ["1914", "1918", "1939", "1905"]),
    C("What is the largest island in the Mediterranean Sea?",
      ["Sicily", "Sardinia", "Cyprus", "Crete"],
      "Która wyspa jest największa na Morzu Śródziemnym?",
      ["Sycylia", "Sardynia", "Cypr", "Kreta"],
      "Was ist die größte Insel im Mittelmeer?",
      ["Sizilien", "Sardinien", "Zypern", "Kreta"]),
    C("Who wrote War and Peace?",
      ["Leo Tolstoy", "Fyodor Dostoevsky", "Nikolai Gogol", "Ivan Goncharov"],
      "Kto napisał 'Wojnę i pokój'?",
      ["Lew Tołstoj", "Fiodor Dostojewski", "Nikołaj Gogol", "Iwan Gonczarow"],
      "Wer schrieb 'Krieg und Frieden'?",
      ["Leo Tolstoi", "Fjodor Dostojewski", "Nikolai Gogol", "Iwan Gontscharow"]),
    C("Which gland is often called the master gland of the body?",
      ["Pituitary", "Thyroid", "Adrenal", "Pineal"],
      "Który gruczoł bywa nazywany gruczołem nadrzędnym organizmu?",
      ["Przysadka mózgowa", "Tarczyca", "Nadnercze", "Szyszynka"],
      "Welche Drüse heißt oft die übergeordnete Drüse des Körpers?",
      ["Hirnanhangdrüse", "Schilddrüse", "Nebenniere", "Zirbeldrüse"]),
    C("Who introduced movable-type printing to Europe?",
      ["Johannes Gutenberg", "William Caxton", "Aldus Manutius", "Benjamin Franklin"],
      "Kto wprowadził w Europie druk z ruchomą czcionką?",
      ["Johannes Gutenberg", "William Caxton", "Aldus Manutius", "Benjamin Franklin"],
      "Wer brachte den Buchdruck mit beweglichen Lettern nach Europa?",
      ["Johannes Gutenberg", "William Caxton", "Aldus Manutius", "Benjamin Franklin"]),
    C("What is the capital of Denmark?",
      ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
      "Jaka jest stolica Danii?",
      ["Kopenhaga", "Aarhus", "Odense", "Aalborg"],
      "Was ist die Hauptstadt Dänemarks?",
      ["Kopenhagen", "Aarhus", "Odense", "Aalborg"]),
    C("Who composed the Brandenburg Concertos?",
      ["Johann Sebastian Bach", "Georg Philipp Telemann", "Antonio Vivaldi", "Joseph Haydn"],
      "Kto skomponował Koncerty brandenburskie?",
      ["Johann Sebastian Bach", "Georg Philipp Telemann", "Antonio Vivaldi", "Joseph Haydn"],
      "Wer komponierte die Brandenburgischen Konzerte?",
      ["Johann Sebastian Bach", "Georg Philipp Telemann", "Antonio Vivaldi", "Joseph Haydn"]),
    C("Who was the first woman to travel into space?",
      ["Valentina Tereshkova", "Sally Ride", "Svetlana Savitskaya", "Mae Jemison"],
      "Kto jako pierwsza kobieta poleciała w kosmos?",
      ["Walentina Tierieszkowa", "Sally Ride", "Swietłana Sawicka", "Mae Jemison"],
      "Wer flog als erste Frau ins All?",
      ["Walentina Tereschkowa", "Sally Ride", "Swetlana Sawizkaja", "Mae Jemison"]),
    C("Which mountain range includes Mont Blanc?",
      ["Alps", "Pyrenees", "Carpathians", "Apennines"],
      "W którym łańcuchu górskim leży Mont Blanc?",
      ["W Alpach", "W Pirenejach", "W Karpatach", "W Apeninach"],
      "In welchem Gebirge liegt der Mont Blanc?",
      ["Alpen", "Pyrenäen", "Karpaten", "Apenninen"]),
    C("What is the chemical symbol for iron?",
      ["Fe", "Ir", "In", "Fr"],
      "Jaki jest symbol chemiczny żelaza?",
      ["Fe", "Ir", "In", "Fr"],
      "Was ist das chemische Symbol für Eisen?",
      ["Fe", "Ir", "In", "Fr"]),
    C("Who wrote The Little Prince?",
      ["Antoine de Saint-Exupéry", "Jules Verne", "Victor Hugo", "Albert Camus"],
      "Kto napisał 'Małego Księcia'?",
      ["Antoine de Saint-Exupéry", "Jules Verne", "Victor Hugo", "Albert Camus"],
      "Wer schrieb 'Der kleine Prinz'?",
      ["Antoine de Saint-Exupéry", "Jules Verne", "Victor Hugo", "Albert Camus"]),
    C("In which city does the Brandenburg Gate stand?",
      ["Berlin", "Potsdam", "Leipzig", "Dresden"],
      "W którym mieście stoi Brama Brandenburska?",
      ["W Berlinie", "W Poczdamie", "W Lipsku", "W Dreźnie"],
      "In welcher Stadt steht das Brandenburger Tor?",
      ["Berlin", "Potsdam", "Leipzig", "Dresden"]),
    C("What is the largest lake in Africa by area?",
      ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"],
      "Które jezioro jest największe powierzchniowo w Afryce?",
      ["Wiktoria", "Tanganika", "Malawi", "Czad"],
      "Welcher See ist flächenmäßig der größte Afrikas?",
      ["Victoriasee", "Tanganjikasee", "Malawisee", "Tschadsee"]),
    C("Who formulated the three laws of planetary motion?",
      ["Johannes Kepler", "Isaac Newton", "Galileo Galilei", "Tycho Brahe"],
      "Kto sformułował trzy prawa ruchu planet?",
      ["Johannes Kepler", "Isaac Newton", "Galileusz", "Tycho Brahe"],
      "Wer formulierte die drei Gesetze der Planetenbewegung?",
      ["Johannes Kepler", "Isaac Newton", "Galileo Galilei", "Tycho Brahe"]),
    C("Which Polish city was the birthplace of the Solidarity movement?",
      ["Gdańsk", "Warsaw", "Wrocław", "Katowice"],
      "W którym polskim mieście zrodził się ruch Solidarność?",
      ["W Gdańsku", "W Warszawie", "We Wrocławiu", "W Katowicach"],
      "In welcher polnischen Stadt entstand die Solidarność-Bewegung?",
      ["Danzig", "Warschau", "Breslau", "Kattowitz"]),
    C("What is the capital of Slovakia?",
      ["Bratislava", "Košice", "Brno", "Ljubljana"],
      "Jaka jest stolica Słowacji?",
      ["Bratysława", "Koszyce", "Brno", "Lublana"],
      "Was ist die Hauptstadt der Slowakei?",
      ["Bratislava", "Košice", "Brünn", "Ljubljana"]),
    C("Who painted the Water Lilies series?",
      ["Claude Monet", "Edgar Degas", "Pierre-Auguste Renoir", "Édouard Manet"],
      "Kto namalował cykl 'Nenufary'?",
      ["Claude Monet", "Edgar Degas", "Pierre-Auguste Renoir", "Édouard Manet"],
      "Wer malte die Serie der Seerosen?",
      ["Claude Monet", "Edgar Degas", "Pierre-Auguste Renoir", "Édouard Manet"]),
    C("Which particle shares the atomic nucleus with the proton?",
      ["Neutron", "Electron", "Photon", "Positron"],
      "Która cząstka dzieli jądro atomowe z protonem?",
      ["Neutron", "Elektron", "Foton", "Pozyton"],
      "Welches Teilchen teilt den Atomkern mit dem Proton?",
      ["Neutron", "Elektron", "Photon", "Positron"]),
    C("Who directed the silent film Metropolis?",
      ["Fritz Lang", "F.W. Murnau", "Ernst Lubitsch", "G.W. Pabst"],
      "Kto wyreżyserował niemy film 'Metropolis'?",
      ["Fritz Lang", "F.W. Murnau", "Ernst Lubitsch", "G.W. Pabst"],
      "Wer führte bei dem Stummfilm 'Metropolis' Regie?",
      ["Fritz Lang", "F.W. Murnau", "Ernst Lubitsch", "G.W. Pabst"]),
]

L8 = [
    C("Who wrote Madame Bovary?",
      ["Gustave Flaubert", "Émile Zola", "Honoré de Balzac", "Stendhal"],
      "Kto napisał 'Panią Bovary'?",
      ["Gustave Flaubert", "Émile Zola", "Honoré de Balzac", "Stendhal"],
      "Wer schrieb 'Madame Bovary'?",
      ["Gustave Flaubert", "Émile Zola", "Honoré de Balzac", "Stendhal"]),
    C("What is the capital of Croatia?",
      ["Zagreb", "Split", "Dubrovnik", "Ljubljana"],
      "Jaka jest stolica Chorwacji?",
      ["Zagrzeb", "Split", "Dubrownik", "Lublana"],
      "Was ist die Hauptstadt Kroatiens?",
      ["Zagreb", "Split", "Dubrovnik", "Ljubljana"]),
    C("Which German philosopher wrote Critique of Pure Reason?",
      ["Immanuel Kant", "Georg Hegel", "Friedrich Nietzsche", "Arthur Schopenhauer"],
      "Który niemiecki filozof napisał 'Krytykę czystego rozumu'?",
      ["Immanuel Kant", "Georg Hegel", "Friedrich Nietzsche", "Arthur Schopenhauer"],
      "Welcher deutsche Philosoph schrieb die 'Kritik der reinen Vernunft'?",
      ["Immanuel Kant", "Georg Hegel", "Friedrich Nietzsche", "Arthur Schopenhauer"]),
    C("Which form of carbon is the main material in pencil lead?",
      ["Graphite", "Diamond", "Fullerene", "Charcoal"],
      "Jaka odmiana węgla stanowi rdzeń ołówka?",
      ["Grafit", "Diament", "Fulleren", "Węgiel drzewny"],
      "Welche Form von Kohlenstoff ist der Hauptstoff in Bleistiftminen?",
      ["Graphit", "Diamant", "Fulleren", "Holzkohle"]),
    C("What is the longest river in the United Kingdom?",
      ["Severn", "Thames", "Trent", "Clyde"],
      "Która rzeka jest najdłuższa w Zjednoczonym Królestwie?",
      ["Severn", "Tamiza", "Trent", "Clyde"],
      "Welcher Fluss ist der längste im Vereinigten Königreich?",
      ["Severn", "Themse", "Trent", "Clyde"]),
    C("Who composed The Barber of Seville?",
      ["Gioachino Rossini", "Giuseppe Verdi", "Gaetano Donizetti", "Vincenzo Bellini"],
      "Kto skomponował 'Cyrulika sewilskiego'?",
      ["Gioachino Rossini", "Giuseppe Verdi", "Gaetano Donizetti", "Vincenzo Bellini"],
      "Wer komponierte 'Der Barbier von Sevilla'?",
      ["Gioachino Rossini", "Giuseppe Verdi", "Gaetano Donizetti", "Vincenzo Bellini"]),
    C("In which country is the region of Transylvania?",
      ["Romania", "Hungary", "Bulgaria", "Serbia"],
      "W którym kraju leży Transylwania?",
      ["W Rumunii", "Na Węgrzech", "W Bułgarii", "W Serbii"],
      "In welchem Land liegt Siebenbürgen?",
      ["Rumänien", "Ungarn", "Bulgarien", "Serbien"]),
    C("Who painted The Persistence of Memory, with melting clocks?",
      ["Salvador Dalí", "René Magritte", "Max Ernst", "Joan Miró"],
      "Kto namalował 'Trwałość pamięci' z miękkimi zegarami?",
      ["Salvador Dalí", "René Magritte", "Max Ernst", "Joan Miró"],
      "Wer malte 'Die Beständigkeit der Erinnerung' mit schmelzenden Uhren?",
      ["Salvador Dalí", "René Magritte", "Max Ernst", "Joan Miró"]),
    C("Which organ produces bile?",
      ["Liver", "Pancreas", "Kidney", "Gall bladder"],
      "Który narząd wytwarza żółć?",
      ["Wątroba", "Trzustka", "Nerka", "Pęcherzyk żółciowy"],
      "Welches Organ bildet Galle?",
      ["Leber", "Bauchspeicheldrüse", "Niere", "Gallenblase"]),
    C("What is the capital of Bulgaria?",
      ["Sofia", "Plovdiv", "Varna", "Bucharest"],
      "Jaka jest stolica Bułgarii?",
      ["Sofia", "Płowdiw", "Warna", "Bukareszt"],
      "Was ist die Hauptstadt Bulgariens?",
      ["Sofia", "Plowdiw", "Warna", "Bukarest"]),
    C("Who was Prime Minister of the United Kingdom for most of the Second World War?",
      ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Anthony Eden"],
      "Kto był premierem Zjednoczonego Królestwa przez większą część II wojny światowej?",
      ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Anthony Eden"],
      "Wer war während des größten Teils des Zweiten Weltkriegs britischer Premierminister?",
      ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Anthony Eden"]),
    C("What is the largest moon in the Solar System?",
      ["Ganymede", "Titan", "Callisto", "Io"],
      "Który księżyc jest największy w Układzie Słonecznym?",
      ["Ganimedes", "Tytan", "Kallisto", "Io"],
      "Welcher Mond ist der größte im Sonnensystem?",
      ["Ganymed", "Titan", "Kallisto", "Io"]),
    C("Who wrote Les Misérables?",
      ["Victor Hugo", "Alexandre Dumas", "Gustave Flaubert", "Émile Zola"],
      "Kto napisał 'Nędzników'?",
      ["Victor Hugo", "Alexandre Dumas", "Gustave Flaubert", "Émile Zola"],
      "Wer schrieb 'Die Elenden'?",
      ["Victor Hugo", "Alexandre Dumas", "Gustave Flaubert", "Émile Zola"]),
    C("What is the SI unit of electric current?",
      ["Ampere", "Volt", "Ohm", "Watt"],
      "Jaka jest jednostka natężenia prądu w układzie SI?",
      ["Amper", "Wolt", "Om", "Wat"],
      "Was ist die SI-Einheit der elektrischen Stromstärke?",
      ["Ampere", "Volt", "Ohm", "Watt"]),
    C("In which country are the rock-cut ruins of Petra?",
      ["Jordan", "Egypt", "Syria", "Lebanon"],
      "W którym kraju leżą wykute w skale ruiny Petry?",
      ["W Jordanii", "W Egipcie", "W Syrii", "W Libanie"],
      "In welchem Land liegen die in Fels gehauenen Ruinen von Petra?",
      ["Jordanien", "Ägypten", "Syrien", "Libanon"]),
    C("Who painted The Birth of Venus?",
      ["Sandro Botticelli", "Raphael", "Titian", "Caravaggio"],
      "Kto namalował 'Narodziny Wenus'?",
      ["Sandro Botticelli", "Rafael", "Tycjan", "Caravaggio"],
      "Wer malte 'Die Geburt der Venus'?",
      ["Sandro Botticelli", "Raffael", "Tizian", "Caravaggio"]),
    C("What is the official language of Iran?",
      ["Persian", "Arabic", "Turkish", "Kurdish"],
      "Jaki jest język urzędowy Iranu?",
      ["Perski", "Arabski", "Turecki", "Kurdyjski"],
      "Was ist die Amtssprache des Iran?",
      ["Persisch", "Arabisch", "Türkisch", "Kurdisch"]),
    C("Which battle in 1066 made William the Conqueror king of England?",
      ["Hastings", "Agincourt", "Bannockburn", "Bosworth"],
      "Która bitwa z 1066 roku uczyniła Wilhelma Zdobywcę królem Anglii?",
      ["Hastings", "Azincourt", "Bannockburn", "Bosworth"],
      "Welche Schlacht von 1066 machte Wilhelm den Eroberer zum König Englands?",
      ["Hastings", "Azincourt", "Bannockburn", "Bosworth"]),
    C("What is the chemical symbol for potassium?",
      ["K", "P", "Po", "Pt"],
      "Jaki jest symbol chemiczny potasu?",
      ["K", "P", "Po", "Pt"],
      "Was ist das chemische Symbol für Kalium?",
      ["K", "P", "Po", "Pt"]),
    C("Who wrote One Hundred Years of Solitude?",
      ["Gabriel García Márquez", "Jorge Luis Borges", "Mario Vargas Llosa", "Pablo Neruda"],
      "Kto napisał 'Sto lat samotności'?",
      ["Gabriel García Márquez", "Jorge Luis Borges", "Mario Vargas Llosa", "Pablo Neruda"],
      "Wer schrieb 'Hundert Jahre Einsamkeit'?",
      ["Gabriel García Márquez", "Jorge Luis Borges", "Mario Vargas Llosa", "Pablo Neruda"]),
    C("What is the largest country in Africa by area?",
      ["Algeria", "Sudan", "Democratic Republic of the Congo", "Libya"],
      "Który kraj Afryki jest największy powierzchniowo?",
      ["Algieria", "Sudan", "Demokratyczna Republika Konga", "Libia"],
      "Welches afrikanische Land ist flächenmäßig das größte?",
      ["Algerien", "Sudan", "Demokratische Republik Kongo", "Libyen"]),
    C("Who composed Boléro?",
      ["Maurice Ravel", "Claude Debussy", "Erik Satie", "Camille Saint-Saëns"],
      "Kto skomponował 'Bolero'?",
      ["Maurice Ravel", "Claude Debussy", "Erik Satie", "Camille Saint-Saëns"],
      "Wer komponierte 'Boléro'?",
      ["Maurice Ravel", "Claude Debussy", "Erik Satie", "Camille Saint-Saëns"]),
    C("In Greek myth, who performed the Twelve Labours?",
      ["Heracles", "Achilles", "Odysseus", "Jason"],
      "Kto w mitologii greckiej wykonał dwanaście prac?",
      ["Herakles", "Achilles", "Odyseusz", "Jazon"],
      "Wer vollbrachte in der griechischen Mythologie die zwölf Arbeiten?",
      ["Herakles", "Achilleus", "Odysseus", "Jason"]),
    C("What is the capital of Lithuania?",
      ["Vilnius", "Kaunas", "Riga", "Tallinn"],
      "Jaka jest stolica Litwy?",
      ["Wilno", "Kowno", "Ryga", "Tallinn"],
      "Was ist die Hauptstadt Litauens?",
      ["Wilna", "Kaunas", "Riga", "Tallinn"]),
    C("Who published the general theory of relativity?",
      ["Albert Einstein", "Niels Bohr", "Max Planck", "Erwin Schrödinger"],
      "Kto opublikował ogólną teorię względności?",
      ["Albert Einstein", "Niels Bohr", "Max Planck", "Erwin Schrödinger"],
      "Wer veröffentlichte die allgemeine Relativitätstheorie?",
      ["Albert Einstein", "Niels Bohr", "Max Planck", "Erwin Schrödinger"]),
    C("What is the deepest known oceanic trench?",
      ["Mariana Trench", "Puerto Rico Trench", "Java Trench", "Tonga Trench"],
      "Który rów oceaniczny jest najgłębszy spośród znanych?",
      ["Rów Mariański", "Rów Portorykański", "Rów Jawajski", "Rów Tonga"],
      "Was ist der tiefste bekannte Tiefseegraben?",
      ["Marianengraben", "Puerto-Rico-Graben", "Javagraben", "Tongagraben"]),
    C("Which film includes the line 'Here's looking at you, kid'?",
      ["Casablanca", "Gone with the Wind", "The Maltese Falcon", "Breakfast at Tiffany's"],
      "W którym filmie pada kwestia 'Here's looking at you, kid'?",
      ["Casablanca", "Przeminęło z wiatrem", "Sokół maltański", "Śniadanie u Tiffany'ego"],
      "In welchem Film fällt der Satz 'Here's looking at you, kid'?",
      ["Casablanca", "Vom Winde verweht", "Die Spur des Falken", "Frühstück bei Tiffany"]),
    C("Who was Poland's first democratically elected president after 1989?",
      ["Lech Wałęsa", "Aleksander Kwaśniewski", "Tadeusz Mazowiecki", "Wojciech Jaruzelski"],
      "Kto był pierwszym demokratycznie wybranym prezydentem Polski po 1989 roku?",
      ["Lech Wałęsa", "Aleksander Kwaśniewski", "Tadeusz Mazowiecki", "Wojciech Jaruzelski"],
      "Wer war Polens erster demokratisch gewählter Präsident nach 1989?",
      ["Lech Wałęsa", "Aleksander Kwaśniewski", "Tadeusz Mazowiecki", "Wojciech Jaruzelski"]),
    C("In which German city does the Oktoberfest take place?",
      ["Munich", "Stuttgart", "Frankfurt", "Nuremberg"],
      "W którym niemieckim mieście odbywa się Oktoberfest?",
      ["Monachium", "Stuttgart", "Frankfurt", "Norymberga"],
      "In welcher deutschen Stadt findet das Oktoberfest statt?",
      ["München", "Stuttgart", "Frankfurt", "Nürnberg"]),
    C("What is the seat of the European Central Bank?",
      ["Frankfurt", "Brussels", "Strasbourg", "Berlin"],
      "Gdzie mieści się Europejski Bank Centralny?",
      ["Frankfurt", "Bruksela", "Strasburg", "Berlin"],
      "Wo sitzt die Europäische Zentralbank?",
      ["Frankfurt", "Brüssel", "Straßburg", "Berlin"]),
]

L9 = [
    C("Who wrote The Magic Mountain?",
      ["Thomas Mann", "Franz Kafka", "Hermann Hesse", "Robert Musil"],
      "Kto napisał 'Czarodziejską górę'?",
      ["Thomas Mann", "Franz Kafka", "Hermann Hesse", "Robert Musil"],
      "Wer schrieb 'Der Zauberberg'?",
      ["Thomas Mann", "Franz Kafka", "Hermann Hesse", "Robert Musil"]),
    C("What is the capital of Estonia?",
      ["Tallinn", "Riga", "Vilnius", "Helsinki"],
      "Jaka jest stolica Estonii?",
      ["Tallinn", "Ryga", "Wilno", "Helsinki"],
      "Was ist die Hauptstadt Estlands?",
      ["Tallinn", "Riga", "Wilna", "Helsinki"]),
    C("Which Polish composer wrote the national opera Halka?",
      ["Stanisław Moniuszko", "Fryderyk Chopin", "Karol Szymanowski", "Ignacy Jan Paderewski"],
      "Który polski kompozytor napisał operę narodową 'Halka'?",
      ["Stanisław Moniuszko", "Fryderyk Chopin", "Karol Szymanowski", "Ignacy Jan Paderewski"],
      "Welcher polnische Komponist schrieb die Nationaloper 'Halka'?",
      ["Stanisław Moniuszko", "Frédéric Chopin", "Karol Szymanowski", "Ignacy Jan Paderewski"]),
    C("What is the chemical symbol for tungsten?",
      ["W", "Tu", "Tg", "Tn"],
      "Jaki jest symbol chemiczny wolframu?",
      ["W", "Tu", "Tg", "Tn"],
      "Was ist das chemische Symbol für Wolfram?",
      ["W", "Tu", "Tg", "Tn"]),
    C("Who painted Las Meninas?",
      ["Diego Velázquez", "Francisco Goya", "El Greco", "Bartolomé Murillo"],
      "Kto namalował 'Panny dworskie'?",
      ["Diego Velázquez", "Francisco Goya", "El Greco", "Bartolomé Murillo"],
      "Wer malte 'Las Meninas'?",
      ["Diego Velázquez", "Francisco Goya", "El Greco", "Bartolomé Murillo"]),
    C("In which year did the French Revolution begin?",
      ["1789", "1776", "1815", "1848"],
      "W którym roku wybuchła rewolucja francuska?",
      ["1789", "1776", "1815", "1848"],
      "In welchem Jahr begann die Französische Revolution?",
      ["1789", "1776", "1815", "1848"]),
    C("What is the largest moon of Neptune?",
      ["Triton", "Titan", "Oberon", "Miranda"],
      "Który księżyc Neptuna jest największy?",
      ["Tryton", "Tytan", "Oberon", "Miranda"],
      "Welcher Mond des Neptun ist der größte?",
      ["Triton", "Titan", "Oberon", "Miranda"]),
    C("Who wrote Eugene Onegin?",
      ["Alexander Pushkin", "Mikhail Lermontov", "Nikolai Gogol", "Ivan Turgenev"],
      "Kto napisał 'Eugeniusza Oniegina'?",
      ["Aleksander Puszkin", "Michaił Lermontow", "Nikołaj Gogol", "Iwan Turgieniew"],
      "Wer schrieb 'Eugen Onegin'?",
      ["Alexander Puschkin", "Michail Lermontow", "Nikolai Gogol", "Iwan Turgenew"]),
    C("Which canal links the Mediterranean Sea with the Red Sea?",
      ["Suez Canal", "Panama Canal", "Kiel Canal", "Corinth Canal"],
      "Który kanał łączy Morze Śródziemne z Morzem Czerwonym?",
      ["Kanał Sueski", "Kanał Panamski", "Kanał Kiloński", "Kanał Koryncki"],
      "Welcher Kanal verbindet das Mittelmeer mit dem Roten Meer?",
      ["Sueskanal", "Panamakanal", "Nord-Ostsee-Kanal", "Kanal von Korinth"]),
    C("Who first described the circulation of blood in humans?",
      ["William Harvey", "Andreas Vesalius", "Edward Jenner", "Ignaz Semmelweis"],
      "Kto jako pierwszy opisał krążenie krwi u człowieka?",
      ["William Harvey", "Andreas Vesalius", "Edward Jenner", "Ignaz Semmelweis"],
      "Wer beschrieb als Erster den Blutkreislauf des Menschen?",
      ["William Harvey", "Andreas Vesalius", "Edward Jenner", "Ignaz Semmelweis"]),
    C("What is the capital of Iceland?",
      ["Reykjavík", "Akureyri", "Oslo", "Tórshavn"],
      "Jaka jest stolica Islandii?",
      ["Reykjavík", "Akureyri", "Oslo", "Tórshavn"],
      "Was ist die Hauptstadt Islands?",
      ["Reykjavík", "Akureyri", "Oslo", "Tórshavn"]),
    C("Who composed the opera Tristan und Isolde?",
      ["Richard Wagner", "Richard Strauss", "Carl Maria von Weber", "Giacomo Meyerbeer"],
      "Kto skomponował operę 'Tristan i Izolda'?",
      ["Richard Wagner", "Richard Strauss", "Carl Maria von Weber", "Giacomo Meyerbeer"],
      "Wer komponierte die Oper 'Tristan und Isolde'?",
      ["Richard Wagner", "Richard Strauss", "Carl Maria von Weber", "Giacomo Meyerbeer"]),
    C("What is the second most abundant element in Earth's crust?",
      ["Silicon", "Aluminium", "Iron", "Calcium"],
      "Który pierwiastek jest drugi pod względem obfitości w skorupie ziemskiej?",
      ["Krzem", "Glin", "Żelazo", "Wapń"],
      "Welches Element ist in der Erdkruste das zweithäufigste?",
      ["Silicium", "Aluminium", "Eisen", "Calcium"]),
    C("Who wrote the novel Ulysses, set in Dublin?",
      ["James Joyce", "Oscar Wilde", "W.B. Yeats", "Samuel Beckett"],
      "Kto napisał powieść 'Ulisses', której akcja toczy się w Dublinie?",
      ["James Joyce", "Oscar Wilde", "W.B. Yeats", "Samuel Beckett"],
      "Wer schrieb den in Dublin spielenden Roman 'Ulysses'?",
      ["James Joyce", "Oscar Wilde", "W.B. Yeats", "Samuel Beckett"]),
    C("In which Italian city is the Uffizi Gallery?",
      ["Florence", "Rome", "Venice", "Milan"],
      "W którym włoskim mieście znajduje się Galeria Uffizi?",
      ["We Florencji", "W Rzymie", "W Wenecji", "W Mediolanie"],
      "In welcher italienischen Stadt liegt die Uffizien?",
      ["Florenz", "Rom", "Venedig", "Mailand"]),
    C("What is the SI unit of frequency?",
      ["Hertz", "Watt", "Tesla", "Becquerel"],
      "Jaka jest jednostka częstotliwości w układzie SI?",
      ["Herc", "Wat", "Tesla", "Bekerel"],
      "Was ist die SI-Einheit der Frequenz?",
      ["Hertz", "Watt", "Tesla", "Becquerel"]),
    C("Who was crowned Emperor of the Romans in the year 800?",
      ["Charlemagne", "Otto I", "Constantine", "Frederick Barbarossa"],
      "Kogo koronowano na cesarza Rzymian w roku 800?",
      ["Karola Wielkiego", "Ottona I", "Konstantyna", "Fryderyka Barbarossę"],
      "Wer wurde im Jahr 800 zum Kaiser der Römer gekrönt?",
      ["Karl der Große", "Otto I.", "Konstantin", "Friedrich Barbarossa"]),
    C("The 1920 Polish victory near Warsaw is often called the Miracle on the what?",
      ["Vistula", "Oder", "Elbe", "Danube"],
      "Zwycięstwo Polski spod Warszawy z 1920 roku nazywa się Cudem nad którą rzeką?",
      ["Wisłą", "Odrą", "Łabą", "Dunajem"],
      "Der polnische Sieg bei Warschau 1920 heißt oft das Wunder an welchem Fluss?",
      ["Weichsel", "Oder", "Elbe", "Donau"]),
    C("Who directed the film Battleship Potemkin?",
      ["Sergei Eisenstein", "Andrei Tarkovsky", "Dziga Vertov", "Vsevolod Pudovkin"],
      "Kto wyreżyserował film 'Pancernik Potiomkin'?",
      ["Siergiej Eisenstein", "Andriej Tarkowski", "Dziga Wiertow", "Wsiewołod Pudowkin"],
      "Wer führte bei dem Film 'Panzerkreuzer Potemkin' Regie?",
      ["Sergei Eisenstein", "Andrei Tarkowski", "Dsiga Wertow", "Wsewolod Pudowkin"]),
    C("Who is credited with creating the first widely used periodic table?",
      ["Dmitri Mendeleev", "John Dalton", "Antoine Lavoisier", "Jöns Berzelius"],
      "Komu przypisuje się stworzenie pierwszego powszechnie używanego układu okresowego?",
      ["Dmitrij Mendelejew", "John Dalton", "Antoine Lavoisier", "Jöns Berzelius"],
      "Wem wird die erste weit verbreitete Periodentafel zugeschrieben?",
      ["Dmitri Mendelejew", "John Dalton", "Antoine Lavoisier", "Jöns Berzelius"]),
    C("What is the capital of Serbia?",
      ["Belgrade", "Novi Sad", "Zagreb", "Sarajevo"],
      "Jaka jest stolica Serbii?",
      ["Belgrad", "Nowy Sad", "Zagrzeb", "Sarajewo"],
      "Was ist die Hauptstadt Serbiens?",
      ["Belgrad", "Novi Sad", "Zagreb", "Sarajevo"]),
    C("Who painted The Garden of Earthly Delights?",
      ["Hieronymus Bosch", "Pieter Bruegel", "Jan van Eyck", "Albrecht Dürer"],
      "Kto namalował 'Ogród rozkoszy ziemskich'?",
      ["Hieronim Bosch", "Pieter Bruegel", "Jan van Eyck", "Albrecht Dürer"],
      "Wer malte 'Der Garten der Lüste'?",
      ["Hieronymus Bosch", "Pieter Bruegel", "Jan van Eyck", "Albrecht Dürer"]),
    C("Who discovered the neutron?",
      ["James Chadwick", "Ernest Rutherford", "J.J. Thomson", "Niels Bohr"],
      "Kto odkrył neutron?",
      ["James Chadwick", "Ernest Rutherford", "J.J. Thomson", "Niels Bohr"],
      "Wer entdeckte das Neutron?",
      ["James Chadwick", "Ernest Rutherford", "J.J. Thomson", "Niels Bohr"]),
    C("Who wrote The Decameron?",
      ["Giovanni Boccaccio", "Dante Alighieri", "Petrarch", "Niccolò Machiavelli"],
      "Kto napisał 'Dekameron'?",
      ["Giovanni Boccaccio", "Dante Alighieri", "Petrarka", "Niccolò Machiavelli"],
      "Wer schrieb das 'Dekameron'?",
      ["Giovanni Boccaccio", "Dante Alighieri", "Petrarca", "Niccolò Machiavelli"]),
    C("Who composed the orchestral suite The Planets?",
      ["Gustav Holst", "Edward Elgar", "Ralph Vaughan Williams", "Benjamin Britten"],
      "Kto skomponował suitę orkiestrową 'Planety'?",
      ["Gustav Holst", "Edward Elgar", "Ralph Vaughan Williams", "Benjamin Britten"],
      "Wer komponierte die Orchestersuite 'Die Planeten'?",
      ["Gustav Holst", "Edward Elgar", "Ralph Vaughan Williams", "Benjamin Britten"]),
    C("In which modern country are the ruins of ancient Carthage?",
      ["Tunisia", "Libya", "Algeria", "Morocco"],
      "W którym współczesnym kraju leżą ruiny starożytnej Kartaginy?",
      ["W Tunezji", "W Libii", "W Algierii", "W Maroku"],
      "In welchem heutigen Land liegen die Ruinen des antiken Karthago?",
      ["Tunesien", "Libyen", "Algerien", "Marokko"]),
    C("What does the Richter scale measure?",
      ["Earthquake magnitude", "Wind speed", "Ocean depth", "Air pressure"],
      "Co mierzy skala Richtera?",
      ["Siłę trzęsienia ziemi", "Prędkość wiatru", "Głębokość oceanu", "Ciśnienie powietrza"],
      "Was misst die Richterskala?",
      ["Erdbebenstärke", "Windgeschwindigkeit", "Meerestiefe", "Luftdruck"]),
]

L10 = [
    C("Who wrote The Tin Drum?",
      ["Günter Grass", "Heinrich Böll", "Bertolt Brecht", "Thomas Mann"],
      "Kto napisał 'Blaszany bębenek'?",
      ["Günter Grass", "Heinrich Böll", "Bertolt Brecht", "Thomas Mann"],
      "Wer schrieb 'Die Blechtrommel'?",
      ["Günter Grass", "Heinrich Böll", "Bertolt Brecht", "Thomas Mann"]),
    C("What is the capital of Moldova?",
      ["Chișinău", "Iași", "Odessa", "Bucharest"],
      "Jaka jest stolica Mołdawii?",
      ["Kiszyniów", "Jassy", "Odessa", "Bukareszt"],
      "Was ist die Hauptstadt der Republik Moldau?",
      ["Kischinau", "Jassy", "Odessa", "Bukarest"]),
    C("Near which Polish city is the historic Wieliczka salt mine?",
      ["Kraków", "Wrocław", "Katowice", "Lublin"],
      "Przy którym polskim mieście leży zabytkowa kopalnia soli w Wieliczce?",
      ["Przy Krakowie", "Przy Wrocławiu", "Przy Katowicach", "Przy Lublinie"],
      "Bei welcher polnischen Stadt liegt das historische Salzbergwerk Wieliczka?",
      ["Krakau", "Breslau", "Kattowitz", "Lublin"]),
    C("What is the chemical symbol for lead?",
      ["Pb", "Ld", "Le", "Pl"],
      "Jaki jest symbol chemiczny ołowiu?",
      ["Pb", "Ld", "Le", "Pl"],
      "Was ist das chemische Symbol für Blei?",
      ["Pb", "Ld", "Le", "Pl"]),
    C("Who painted The Arnolfini Portrait?",
      ["Jan van Eyck", "Hans Holbein", "Rogier van der Weyden", "Albrecht Dürer"],
      "Kto namalował 'Portret małżonków Arnolfinich'?",
      ["Jan van Eyck", "Hans Holbein", "Rogier van der Weyden", "Albrecht Dürer"],
      "Wer malte das Arnolfini-Porträt?",
      ["Jan van Eyck", "Hans Holbein", "Rogier van der Weyden", "Albrecht Dürer"]),
    C("In which year was Magna Carta sealed?",
      ["1215", "1066", "1314", "1485"],
      "W którym roku pieczęcią opatrzono Magna Cartę?",
      ["1215", "1066", "1314", "1485"],
      "In welchem Jahr wurde die Magna Carta besiegelt?",
      ["1215", "1066", "1314", "1485"]),
    C("What is Pluto's largest moon?",
      ["Charon", "Nix", "Hydra", "Styx"],
      "Który księżyc Plutona jest największy?",
      ["Charon", "Nix", "Hydra", "Styx"],
      "Welcher Mond des Pluto ist der größte?",
      ["Charon", "Nix", "Hydra", "Styx"]),
    C("Who wrote Dead Souls?",
      ["Nikolai Gogol", "Ivan Turgenev", "Anton Chekhov", "Maxim Gorky"],
      "Kto napisał 'Martwe dusze'?",
      ["Nikołaj Gogol", "Iwan Turgieniew", "Anton Czechow", "Maksim Gorki"],
      "Wer schrieb 'Die toten Seelen'?",
      ["Nikolai Gogol", "Iwan Turgenew", "Anton Tschechow", "Maxim Gorki"]),
    C("In which German city does the Porta Nigra stand?",
      ["Trier", "Mainz", "Cologne", "Aachen"],
      "W którym niemieckim mieście stoi Porta Nigra?",
      ["W Trewirze", "W Moguncji", "W Kolonii", "W Akwizgranie"],
      "In welcher deutschen Stadt steht die Porta Nigra?",
      ["Trier", "Mainz", "Köln", "Aachen"]),
    C("Who is credited with discovering the electron?",
      ["J.J. Thomson", "Ernest Rutherford", "James Chadwick", "Robert Millikan"],
      "Komu przypisuje się odkrycie elektronu?",
      ["J.J. Thomson", "Ernest Rutherford", "James Chadwick", "Robert Millikan"],
      "Wem wird die Entdeckung des Elektrons zugeschrieben?",
      ["J.J. Thomson", "Ernest Rutherford", "James Chadwick", "Robert Millikan"]),
    C("What is the capital of Latvia?",
      ["Riga", "Tallinn", "Vilnius", "Liepāja"],
      "Jaka jest stolica Łotwy?",
      ["Ryga", "Tallinn", "Wilno", "Lipawa"],
      "Was ist die Hauptstadt Lettlands?",
      ["Riga", "Tallinn", "Wilna", "Libau"]),
    C("Who composed the opera Der Rosenkavalier?",
      ["Richard Strauss", "Richard Wagner", "Alban Berg", "Arnold Schoenberg"],
      "Kto skomponował operę 'Kawaler srebrnej róży'?",
      ["Richard Strauss", "Richard Wagner", "Alban Berg", "Arnold Schönberg"],
      "Wer komponierte die Oper 'Der Rosenkavalier'?",
      ["Richard Strauss", "Richard Wagner", "Alban Berg", "Arnold Schönberg"]),
    C("A deficiency of which vitamin causes scurvy?",
      ["Vitamin C", "Vitamin A", "Vitamin B12", "Vitamin D"],
      "Niedobór której witaminy powoduje szkorbut?",
      ["Witaminy C", "Witaminy A", "Witaminy B12", "Witaminy D"],
      "Ein Mangel welches Vitamins verursacht Skorbut?",
      ["Vitamin C", "Vitamin A", "Vitamin B12", "Vitamin D"]),
    C("Who directed The Seventh Seal?",
      ["Ingmar Bergman", "Federico Fellini", "Akira Kurosawa", "Michelangelo Antonioni"],
      "Kto wyreżyserował 'Siódmą pieczęć'?",
      ["Ingmar Bergman", "Federico Fellini", "Akira Kurosawa", "Michelangelo Antonioni"],
      "Wer führte bei 'Das siebente Siegel' Regie?",
      ["Ingmar Bergman", "Federico Fellini", "Akira Kurosawa", "Michelangelo Antonioni"]),
    C("What is the SI unit of pressure?",
      ["Pascal", "Bar", "Newton", "Joule"],
      "Jaka jest jednostka ciśnienia w układzie SI?",
      ["Paskal", "Bar", "Niuton", "Dżul"],
      "Was ist die SI-Einheit des Drucks?",
      ["Pascal", "Bar", "Newton", "Joule"]),
    C("Who was the last Emperor of Russia?",
      ["Nicholas II", "Alexander III", "Peter the Great", "Ivan the Terrible"],
      "Kto był ostatnim cesarzem Rosji?",
      ["Mikołaj II", "Aleksander III", "Piotr Wielki", "Iwan Groźny"],
      "Wer war der letzte Kaiser Russlands?",
      ["Nikolaus II.", "Alexander III.", "Peter der Große", "Iwan der Schreckliche"]),
    C("Which 1815 battle ended Napoleon's rule?",
      ["Waterloo", "Austerlitz", "Leipzig", "Trafalgar"],
      "Która bitwa z 1815 roku zakończyła rządy Napoleona?",
      ["Waterloo", "Austerlitz", "Lipsk", "Trafalgar"],
      "Welche Schlacht von 1815 beendete Napoleons Herrschaft?",
      ["Waterloo", "Austerlitz", "Leipzig", "Trafalgar"]),
    C("What is the world's largest island?",
      ["Greenland", "New Guinea", "Borneo", "Madagascar"],
      "Która wyspa jest największa na świecie?",
      ["Grenlandia", "Nowa Gwinea", "Borneo", "Madagaskar"],
      "Was ist die größte Insel der Welt?",
      ["Grönland", "Neuguinea", "Borneo", "Madagaskar"]),
    C("Who formulated the uncertainty principle in quantum mechanics?",
      ["Werner Heisenberg", "Erwin Schrödinger", "Max Born", "Wolfgang Pauli"],
      "Kto sformułował zasadę nieoznaczoności w mechanice kwantowej?",
      ["Werner Heisenberg", "Erwin Schrödinger", "Max Born", "Wolfgang Pauli"],
      "Wer formulierte die Unschärferelation der Quantenmechanik?",
      ["Werner Heisenberg", "Erwin Schrödinger", "Max Born", "Wolfgang Pauli"]),
    C("What is the capital of Slovenia?",
      ["Ljubljana", "Maribor", "Zagreb", "Trieste"],
      "Jaka jest stolica Słowenii?",
      ["Lublana", "Maribor", "Zagrzeb", "Triest"],
      "Was ist die Hauptstadt Sloweniens?",
      ["Ljubljana", "Maribor", "Zagreb", "Triest"]),
    C("Who painted Liberty Leading the People?",
      ["Eugène Delacroix", "Jacques-Louis David", "Jean-Auguste-Dominique Ingres", "Théodore Géricault"],
      "Kto namalował 'Wolność wiodącą lud na barykady'?",
      ["Eugène Delacroix", "Jacques-Louis David", "Jean-Auguste-Dominique Ingres", "Théodore Géricault"],
      "Wer malte 'Die Freiheit führt das Volk'?",
      ["Eugène Delacroix", "Jacques-Louis David", "Jean-Auguste-Dominique Ingres", "Théodore Géricault"]),
    C("What process in the Sun's core produces its energy?",
      ["Nuclear fusion", "Nuclear fission", "Chemical combustion", "Gravitational collapse"],
      "Jaki proces w jądrze Słońca wytwarza jego energię?",
      ["Synteza jądrowa", "Rozszczepienie jądra", "Spalanie chemiczne", "Zapadanie grawitacyjne"],
      "Welcher Prozess im Kern der Sonne erzeugt ihre Energie?",
      ["Kernfusion", "Kernspaltung", "chemische Verbrennung", "Gravitationskollaps"]),
    C("Who wrote the Latin epic The Aeneid?",
      ["Virgil", "Horace", "Ovid", "Lucan"],
      "Kto napisał łaciński epos 'Eneidę'?",
      ["Wergiliusz", "Horacy", "Owidiusz", "Lukan"],
      "Wer schrieb das lateinische Epos 'Aeneis'?",
      ["Vergil", "Horaz", "Ovid", "Lucan"]),
    C("In which country is the temple complex of Angkor Wat?",
      ["Cambodia", "Thailand", "Vietnam", "Laos"],
      "W którym kraju leży zespół świątynny Angkor Wat?",
      ["W Kambodży", "W Tajlandii", "W Wietnamie", "W Laosie"],
      "In welchem Land liegt der Tempelkomplex Angkor Wat?",
      ["Kambodscha", "Thailand", "Vietnam", "Laos"]),
    C("Who composed the opera La Traviata?",
      ["Giuseppe Verdi", "Giacomo Puccini", "Gioachino Rossini", "Gaetano Donizetti"],
      "Kto skomponował operę 'La Traviata'?",
      ["Giuseppe Verdi", "Giacomo Puccini", "Gioachino Rossini", "Gaetano Donizetti"],
      "Wer komponierte die Oper 'La Traviata'?",
      ["Giuseppe Verdi", "Giacomo Puccini", "Gioachino Rossini", "Gaetano Donizetti"]),
    C("What is the deepest lake on Earth?",
      ["Lake Baikal", "Lake Tanganyika", "Caspian Sea", "Lake Superior"],
      "Które jezioro jest najgłębsze na Ziemi?",
      ["Bajkał", "Tanganika", "Morze Kaspijskie", "Górne"],
      "Was ist der tiefste See der Erde?",
      ["Baikalsee", "Tanganjikasee", "Kaspisches Meer", "Oberer See"]),
    C("Who calculated Earth's circumference in antiquity with remarkable accuracy?",
      ["Eratosthenes", "Ptolemy", "Aristotle", "Archimedes"],
      "Kto w starożytności obliczył obwód Ziemi z niezwykłą dokładnością?",
      ["Eratostenes", "Ptolemeusz", "Arystoteles", "Archimedes"],
      "Wer berechnete in der Antike den Erdumfang mit bemerkenswerter Genauigkeit?",
      ["Eratosthenes", "Ptolemaios", "Aristoteles", "Archimedes"]),
]
