# Extra question levels. Answer lists: index 0 is always correct.
from qfmt import C

L2 = [
    C("Which city is the capital of France?",
      ["Paris", "Lyon", "Marseille", "Nice"],
      "Które miasto jest stolicą Francji?",
      ["Paryż", "Lyon", "Marsylia", "Nicea"],
      "Welche Stadt ist die Hauptstadt Frankreichs?",
      ["Paris", "Lyon", "Marseille", "Nizza"]),
    C("How many minutes are there in one hour?",
      ["60", "24", "100", "30"],
      "Ile minut ma jedna godzina?",
      ["60", "24", "100", "30"],
      "Wie viele Minuten hat eine Stunde?",
      ["60", "24", "100", "30"]),
    C("Which ocean is the largest?",
      ["Pacific", "Atlantic", "Indian", "Arctic"],
      "Który ocean jest największy?",
      ["Spokojny", "Atlantycki", "Indyjski", "Arktyczny"],
      "Welcher Ozean ist der größte?",
      ["Pazifik", "Atlantik", "Indischer Ozean", "Arktischer Ozean"]),
    C("What gas do plants absorb from the air?",
      ["Carbon dioxide", "Helium", "Neon", "Ozone only"],
      "Jaki gaz rośliny pobierają z powietrza?",
      ["Dwutlenek węgla", "Hel", "Neon", "Tylko ozon"],
      "Welches Gas nehmen Pflanzen aus der Luft auf?",
      ["Kohlenstoffdioxid", "Helium", "Neon", "Nur Ozon"]),
    C("Which instrument has 88 keys on a standard concert version?",
      ["Piano", "Violin", "Flute", "Drum kit"],
      "Który instrument ma w wersji koncertowej 88 klawiszy?",
      ["Fortepian", "Skrzypce", "Flet", "Perkusja"],
      "Welches Konzertinstrument hat 88 Tasten?",
      ["Klavier", "Geige", "Flöte", "Schlagzeug"]),
    C("In which country are the pyramids of Giza?",
      ["Egypt", "Mexico", "India", "Greece"],
      "W którym kraju stoją piramidy w Gizie?",
      ["Egipt", "Meksyk", "Indie", "Grecja"],
      "In welchem Land stehen die Pyramiden von Gizeh?",
      ["Ägypten", "Mexiko", "Indien", "Griechenland"]),
    C("What is the chemical symbol for water?",
      ["H2O", "CO2", "NaCl", "O2"],
      "Jaki jest wzór chemiczny wody?",
      ["H2O", "CO2", "NaCl", "O2"],
      "Was ist die chemische Formel für Wasser?",
      ["H2O", "CO2", "NaCl", "O2"]),
    C("Which sport uses a net and a shuttlecock?",
      ["Badminton", "Polo", "Golf", "Archery"],
      "W którym sporcie używa się siatki i lotki?",
      ["Badminton", "Polo", "Golf", "Łucznictwo"],
      "Bei welcher Sportart gibt es Netz und Federball?",
      ["Badminton", "Polo", "Golf", "Bogenschießen"]),
    C("Who painted the Mona Lisa?",
      ["Leonardo da Vinci", "Picasso", "Van Gogh", "Michelangelo"],
      "Kto namalował Monę Lisę?",
      ["Leonardo da Vinci", "Picasso", "Van Gogh", "Michał Anioł"],
      "Wer malte die Mona Lisa?",
      ["Leonardo da Vinci", "Picasso", "Van Gogh", "Michelangelo"]),
    C("What is the largest mammal?",
      ["Blue whale", "African elephant", "Giraffe", "Hippopotamus"],
      "Który ssak jest największy na Ziemi?",
      ["Płetwal błękitny", "Słoń afrykański", "Żyrafa", "Hipopotam"],
      "Was ist das größte Säugetier?",
      ["Blauwal", "Afrikanischer Elefant", "Giraffe", "Nilpferd"]),
    C("Which continent is Brazil on?",
      ["South America", "Africa", "Europe", "Asia"],
      "Na którym kontynencie leży Brazylia?",
      ["Ameryka Południowa", "Afryka", "Europa", "Azja"],
      "Auf welchem Kontinent liegt Brasilien?",
      ["Südamerika", "Afrika", "Europa", "Asien"]),
    C("How many sides does a hexagon have?",
      ["6", "5", "8", "7"],
      "Ile boków ma sześciokąt?",
      ["6", "5", "8", "7"],
      "Wie viele Seiten hat ein Sechseck?",
      ["6", "5", "8", "7"]),
    C("What is the boiling point of water at standard pressure, in Celsius?",
      ["100", "0", "50", "212"],
      "Jaka jest temperatura wrzenia wody przy ciśnieniu standardowym (w °C)?",
      ["100", "0", "50", "212"],
      "Bei wie viel Grad Celsius kocht Wasser unter Normaldruck?",
      ["100", "0", "50", "212"]),
    C("Which of these is a reptile?",
      ["Snake", "Frog", "Dolphin", "Penguin"],
      "Które z tych zwierząt jest gadem?",
      ["Wąż", "Żaba", "Delfin", "Pingwin"],
      "Welches dieser Tiere ist ein Reptil?",
      ["Schlange", "Frosch", "Delfin", "Pinguin"]),
    C("In chess, which piece can move any number of squares diagonally?",
      ["Bishop", "Knight", "King", "Pawn"],
      "W szachach która figura chodzi dowolnie po przekątnych?",
      ["Goniec", "Skoczek", "Król", "Pion"],
      "Welche Schachfigur zieht beliebig weit diagonal?",
      ["Läufer", "Springer", "König", "Bauer"]),
    C("What language is the word 'kindergarten' originally from?",
      ["German", "French", "Latin", "Dutch"],
      "Z jakiego języka pochodzi słowo 'kindergarten'?",
      ["Niemieckiego", "Francuskiego", "Łaciny", "Niderlandzkiego"],
      "Aus welcher Sprache stammt das Wort 'Kindergarten' ursprünglich?",
      ["Deutsch", "Französisch", "Latein", "Niederländisch"]),
    C("Which planet is known as the Red Planet?",
      ["Mars", "Venus", "Mercury", "Saturn"],
      "Która planeta nazywana jest Czerwoną Planetą?",
      ["Mars", "Wenus", "Merkury", "Saturn"],
      "Welcher Planet heißt der Rote Planet?",
      ["Mars", "Venus", "Merkur", "Saturn"]),
    C("What do you call a three-lined Japanese poem?",
      ["Haiku", "Sonnet", "Epic", "Limerick"],
      "Jak nazywa się trzywersowy japoński wiersz?",
      ["Haiku", "Sonet", "Epos", "Limerick"],
      "Wie heißt ein dreizeiliges japanisches Gedicht?",
      ["Haiku", "Sonett", "Epos", "Limerick"]),
    C("Which metal is liquid at room temperature?",
      ["Mercury", "Iron", "Copper", "Aluminium"],
      "Który metal jest ciekły w temperaturze pokojowej?",
      ["Rtęć", "Żelazo", "Miedź", "Aluminium"],
      "Welches Metall ist bei Zimmertemperatur flüssig?",
      ["Quecksilber", "Eisen", "Kupfer", "Aluminium"]),
    C("What is the capital of Poland?",
      ["Warsaw", "Kraków", "Gdańsk", "Wrocław"],
      "Jaka jest stolica Polski?",
      ["Warszawa", "Kraków", "Gdańsk", "Wrocław"],
      "Was ist die Hauptstadt Polens?",
      ["Warschau", "Krakau", "Danzig", "Breslau"]),
    C("How many players are on the field for one football (soccer) team?",
      ["11", "9", "15", "7"],
      "Ilu zawodników jednej drużyny jest na boisku w piłce nożnej?",
      ["11", "9", "15", "7"],
      "Wie viele Spieler einer Fußballmannschaft stehen auf dem Feld?",
      ["11", "9", "15", "7"]),
    C("Which organ pumps blood around the body?",
      ["Heart", "Liver", "Lung", "Kidney"],
      "Który narząd pompuje krew w organizmie?",
      ["Serce", "Wątroba", "Płuco", "Nerka"],
      "Welches Organ pumpt das Blut durch den Körper?",
      ["Herz", "Leber", "Lunge", "Niere"]),
    C("What is the largest country by area?",
      ["Russia", "Canada", "China", "United States"],
      "Który kraj jest największy powierzchniowo?",
      ["Rosja", "Kanada", "Chiny", "Stany Zjednoczone"],
      "Welches Land ist flächenmäßig das größte?",
      ["Russland", "Kanada", "China", "USA"]),
    C("Which fairy tale character leaves a trail of breadcrumbs?",
      ["Hansel", "Cinderella", "Pinocchio", "Aladdin"],
      "Która postać z baśni zostawia ślad z okruchów chleba?",
      ["Jaś", "Kopciuszek", "Pinokio", "Aladyn"],
      "Welche Märchenfigur hinterlässt eine Spur aus Brotkrumen?",
      ["Hänsel", "Aschenputtel", "Pinocchio", "Aladdin"]),
    C("What colour is chlorophyll?",
      ["Green", "Red", "Blue", "White"],
      "Jakiego koloru jest chlorofil?",
      ["Zielonego", "Czerwonego", "Niebieskiego", "Białego"],
      "Welche Farbe hat Chlorophyll?",
      ["Grün", "Rot", "Blau", "Weiß"]),
    C("Which of these cities is in Germany?",
      ["Berlin", "Vienna", "Zurich", "Prague"],
      "Które z tych miast leży w Niemczech?",
      ["Berlin", "Wiedeń", "Zurych", "Praga"],
      "Welche dieser Städte liegt in Deutschland?",
      ["Berlin", "Wien", "Zürich", "Prag"]),
    C("How many strings does a standard violin have?",
      ["4", "6", "5", "8"],
      "Ile strun ma standardowe skrzypce?",
      ["4", "6", "5", "8"],
      "Wie viele Saiten hat eine normale Geige?",
      ["4", "6", "5", "8"]),
    C("What is the main gas in Earth's atmosphere?",
      ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"],
      "Jaki gaz stanowi większość atmosfery Ziemi?",
      ["Azot", "Tlen", "Dwutlenek węgla", "Wodór"],
      "Welches Gas macht den Großteil der Erdatmosphäre aus?",
      ["Stickstoff", "Sauerstoff", "Kohlenstoffdioxid", "Wasserstoff"]),
]

L3 = [
    C("Which river flows through London?",
      ["Thames", "Seine", "Danube", "Rhine"],
      "Która rzeka przepływa przez Londyn?",
      ["Tamiza", "Sekwana", "Dunaj", "Ren"],
      "Welcher Fluss fließt durch London?",
      ["Themse", "Seine", "Donau", "Rhein"]),
    C("Who wrote 'Romeo and Juliet'?",
      ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"],
      "Kto napisał 'Romea i Julię'?",
      ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"],
      "Wer schrieb 'Romeo und Julia'?",
      ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"]),
    C("What is the currency of Japan?",
      ["Yen", "Won", "Yuan", "Baht"],
      "Jaka jest waluta Japonii?",
      ["Jen", "Won", "Yuan", "Baht"],
      "Was ist die Währung Japans?",
      ["Yen", "Won", "Yuan", "Baht"]),
    C("Which bone is the longest in the human body?",
      ["Femur", "Tibia", "Humerus", "Radius"],
      "Która kość jest najdłuższa w ciele człowieka?",
      ["Kość udowa", "Piszczel", "Kość ramienna", "Kość promieniowa"],
      "Welcher Knochen ist der längste im menschlichen Körper?",
      ["Oberschenkelknochen", "Schienbein", "Oberarmknochen", "Speiche"]),
    C("In computing, what does CPU stand for?",
      ["Central Processing Unit", "Computer Personal Utility", "Core Power Upload", "Central Print Unit"],
      "W informatyce, co oznacza skrót CPU?",
      ["Central Processing Unit", "Computer Personal Utility", "Core Power Upload", "Central Print Unit"],
      "Wofür steht CPU in der Informatik?",
      ["Central Processing Unit", "Computer Personal Utility", "Core Power Upload", "Central Print Unit"]),
    C("Which desert is the largest hot desert in the world?",
      ["Sahara", "Gobi", "Kalahari", "Mojave"],
      "Która pustynia jest największą gorącą pustynią świata?",
      ["Sahara", "Gobi", "Kalahari", "Mojave"],
      "Welche ist die größte heiße Wüste der Welt?",
      ["Sahara", "Gobi", "Kalahari", "Mojave"]),
    C("What is the square root of 81?",
      ["9", "8", "7", "18"],
      "Jaki jest pierwiastek kwadratowy z 81?",
      ["9", "8", "7", "18"],
      "Was ist die Quadratwurzel aus 81?",
      ["9", "8", "7", "18"]),
    C("Which composer wrote the 'Moonlight Sonata'?",
      ["Beethoven", "Mozart", "Bach", "Chopin"],
      "Który kompozytor napisał 'Sonatę księżycową'?",
      ["Beethoven", "Mozart", "Bach", "Chopin"],
      "Wer komponierte die 'Mondscheinsonate'?",
      ["Beethoven", "Mozart", "Bach", "Chopin"]),
    C("Mount Everest lies on the border of Nepal and which country?",
      ["China", "India", "Bhutan", "Pakistan"],
      "Mount Everest leży na granicy Nepalu i którego kraju?",
      ["Chin", "Indii", "Bhutanu", "Pakistanu"],
      "Der Mount Everest liegt an der Grenze Nepals zu welchem Land?",
      ["China", "Indien", "Bhutan", "Pakistan"]),
    C("Which blood type is often called the universal donor?",
      ["O negative", "AB positive", "A positive", "B negative"],
      "Która grupa krwi bywa nazywana uniwersalnym dawcą?",
      ["0 Rh−", "AB Rh+", "A Rh+", "B Rh−"],
      "Welche Blutgruppe gilt oft als Universalspender?",
      ["0 negativ", "AB positiv", "A positiv", "B negativ"]),
    C("What is the capital of Australia?",
      ["Canberra", "Sydney", "Melbourne", "Perth"],
      "Jaka jest stolica Australii?",
      ["Canberra", "Sydney", "Melbourne", "Perth"],
      "Was ist die Hauptstadt Australiens?",
      ["Canberra", "Sydney", "Melbourne", "Perth"]),
    C("Which particle has a negative electric charge?",
      ["Electron", "Proton", "Neutron", "Photon"],
      "Która cząstka ma ładunek ujemny?",
      ["Elektron", "Proton", "Neutron", "Foton"],
      "Welches Teilchen hat eine negative Ladung?",
      ["Elektron", "Proton", "Neutron", "Photon"]),
    C("In which sport is the Davis Cup contested?",
      ["Tennis", "Golf", "Cricket", "Rugby"],
      "W jakiej dyscyplinie rozgrywa się Puchar Davisa?",
      ["Tenis", "Golf", "Krykiet", "Rugby"],
      "In welcher Sportart geht es um den Davis Cup?",
      ["Tennis", "Golf", "Cricket", "Rugby"]),
    C("What is the chemical symbol for gold?",
      ["Au", "Ag", "Fe", "Go"],
      "Jaki jest symbol chemiczny złota?",
      ["Au", "Ag", "Fe", "Go"],
      "Was ist das chemische Symbol für Gold?",
      ["Au", "Ag", "Fe", "Go"]),
    C("Which Italian city is famous for its canals?",
      ["Venice", "Rome", "Milan", "Naples"],
      "Które włoskie miasto słynie z kanałów?",
      ["Wenecja", "Rzym", "Mediolan", "Neapol"],
      "Welche italienische Stadt ist für ihre Kanäle berühmt?",
      ["Venedig", "Rom", "Mailand", "Neapel"]),
    C("How many chambers does a human heart have?",
      ["4", "2", "3", "6"],
      "Ile jam ma ludzkie serce?",
      ["4", "2", "3", "6"],
      "Wie viele Kammern hat das menschliche Herz?",
      ["4", "2", "3", "6"]),
    C("Which novel begins with 'Call me Ishmael'?",
      ["Moby-Dick", "Dracula", "Frankenstein", "Jane Eyre"],
      "Która powieść zaczyna się od słów 'Call me Ishmael'?",
      ["Moby Dick", "Drakula", "Frankenstein", "Dziwne losy Jane Eyre"],
      "Welcher Roman beginnt mit 'Call me Ishmael'?",
      ["Moby-Dick", "Dracula", "Frankenstein", "Jane Eyre"]),
    C("What is the smallest prime number?",
      ["2", "1", "3", "0"],
      "Jaka jest najmniejsza liczba pierwsza?",
      ["2", "1", "3", "0"],
      "Was ist die kleinste Primzahl?",
      ["2", "1", "3", "0"]),
    C("Which sea separates Europe from Africa?",
      ["Mediterranean", "Baltic", "Black Sea", "Caspian"],
      "Które morze oddziela Europę od Afryki?",
      ["Śródziemne", "Bałtyckie", "Czarne", "Kaspijskie"],
      "Welches Meer trennt Europa von Afrika?",
      ["Mittelmeer", "Ostsee", "Schwarzes Meer", "Kaspisches Meer"]),
    C("Who discovered penicillin?",
      ["Alexander Fleming", "Marie Curie", "Louis Pasteur", "Edward Jenner"],
      "Kto odkrył penicylinę?",
      ["Alexander Fleming", "Maria Skłodowska-Curie", "Louis Pasteur", "Edward Jenner"],
      "Wer entdeckte Penicillin?",
      ["Alexander Fleming", "Marie Curie", "Louis Pasteur", "Edward Jenner"]),
    C("Which German city hosted the 1972 Summer Olympics?",
      ["Munich", "Berlin", "Hamburg", "Frankfurt"],
      "Które niemieckie miasto gościło igrzyska 1972?",
      ["Monachium", "Berlin", "Hamburg", "Frankfurt"],
      "Welche deutsche Stadt war 1972 Olympia-Gastgeber?",
      ["München", "Berlin", "Hamburg", "Frankfurt"]),
    C("What unit measures electrical resistance?",
      ["Ohm", "Volt", "Watt", "Ampere"],
      "Jaką jednostką mierzy się opór elektryczny?",
      ["Om", "Wolt", "Wat", "Amper"],
      "In welcher Einheit misst man elektrischen Widerstand?",
      ["Ohm", "Volt", "Watt", "Ampere"]),
    C("Which planet has the most prominent rings?",
      ["Saturn", "Mars", "Earth", "Venus"],
      "Która planeta ma najbardziej wyraźne pierścienie?",
      ["Saturn", "Mars", "Ziemia", "Wenus"],
      "Welcher Planet hat die auffälligsten Ringe?",
      ["Saturn", "Mars", "Erde", "Venus"]),
    C("In mythology, who is the Greek god of the sea?",
      ["Poseidon", "Zeus", "Hades", "Apollo"],
      "Kto w mitologii greckiej jest bogiem morza?",
      ["Posejdon", "Zeus", "Hades", "Apollo"],
      "Wer ist in der griechischen Mythologie der Meeresgott?",
      ["Poseidon", "Zeus", "Hades", "Apollon"]),
    C("What is the capital of Canada?",
      ["Ottawa", "Toronto", "Vancouver", "Montreal"],
      "Jaka jest stolica Kanady?",
      ["Ottawa", "Toronto", "Vancouver", "Montreal"],
      "Was ist die Hauptstadt Kanadas?",
      ["Ottawa", "Toronto", "Vancouver", "Montreal"]),
    C("Which vitamin is produced in the skin from sunlight?",
      ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin K"],
      "Która witamina powstaje w skórze pod wpływem słońca?",
      ["Witamina D", "Witamina C", "Witamina A", "Witamina K"],
      "Welches Vitamin bildet die Haut durch Sonnenlicht?",
      ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin K"]),
    C("How many degrees are in a right angle?",
      ["90", "45", "180", "60"],
      "Ile stopni ma kąt prosty?",
      ["90", "45", "180", "60"],
      "Wie viele Grad hat ein rechter Winkel?",
      ["90", "45", "180", "60"]),
    C("Which Polish astronomer proposed a heliocentric model of the solar system?",
      ["Nicolaus Copernicus", "Johannes Kepler", "Galileo Galilei", "Tycho Brahe"],
      "Który polski astronom zaproponował heliocentryczny model Układu Słonecznego?",
      ["Mikołaj Kopernik", "Johannes Kepler", "Galileusz", "Tycho Brahe"],
      "Welcher polnische Astronom schlug ein heliozentrisches Weltbild vor?",
      ["Nikolaus Kopernikus", "Johannes Kepler", "Galileo Galilei", "Tycho Brahe"]),
]
