#!/usr/bin/env python3
"""Generate questions.c from the multilingual trivia bank."""
from __future__ import annotations

import os
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qfmt import esc  # noqa: E402
from bank_l1 import L1  # noqa: E402


def emit(path: str, bank: list) -> None:
    lines = [
        '/* Auto-generated by scripts/gen_questions.py — do not edit by hand. */',
        '#include "questions.h"',
        "",
    ]
    counts = []
    for lv, qs in enumerate(bank):
        lines.append(f"static const Question L{lv}[] = {{")
        for q in qs:
            en_q, en, pl_q, pl, de_q, de = q
            lines.append("  {")
            lines.append(
                '    {"%s", "%s", "%s"},'
                % (esc(en_q), esc(pl_q), esc(de_q))
            )
            lines.append("    {")
            for i in range(4):
                comma = "," if i < 3 else ""
                lines.append(
                    '      {"%s", "%s", "%s"}%s'
                    % (esc(en[i]), esc(pl[i]), esc(de[i]), comma)
                )
            lines.append("    },")
            lines.append("    0")
            lines.append("  },")
        lines.append("};")
        lines.append("")
        counts.append(len(qs))

    lines.append("static const Question *const LEVELS[N_LEVELS] = {")
    lines.append("  " + ", ".join(f"L{i}" for i in range(len(bank))))
    lines.append("};")
    lines.append("")
    lines.append("static const int LEVEL_N[N_LEVELS] = {")
    lines.append("  " + ", ".join(str(n) for n in counts))
    lines.append("};")
    lines.append(
        textwrap.dedent(
            """
            int questions_count(int level) {
              if (level < 0 || level >= N_LEVELS) return 0;
              return LEVEL_N[level];
            }

            const Question *questions_get(int level, int index) {
              if (level < 0 || level >= N_LEVELS) return 0;
              if (index < 0 || index >= LEVEL_N[level]) return 0;
              return &LEVELS[level][index];
            }

            int questions_min_count(void) {
              int i, m = LEVEL_N[0];
              for (i = 1; i < N_LEVELS; i++) {
                if (LEVEL_N[i] < m) m = LEVEL_N[i];
              }
              return m;
            }
            """
        )
    )
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        if not lines[-1].endswith("\n"):
            f.write("\n")
    print(f"Wrote {path}: levels={len(bank)} min={min(counts)} max={max(counts)} total={sum(counts)}")


if __name__ == "__main__":
    from bank_l2_l3 import L2, L3
    from bank_l4_l6 import L4, L5, L6
    from bank_l7_l10 import L7, L8, L9, L10
    from bank_l11_l15 import L11, L12, L13, L14, L15

    bank = [L1, L2, L3, L4, L5, L6, L7, L8, L9, L10, L11, L12, L13, L14, L15]
    if len(bank) != 15:
        raise SystemExit("expected 15 levels")
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(os.path.dirname(here), "questions.c")
    emit(out, bank)
